/* ═══════════════════════════════════════════════════
   VolaLingo v4 — Additions
   Simple stages, daily situations, conversations
   Load AFTER data_v3.js and BEFORE v4.js
   ═══════════════════════════════════════════════════ */

const SIMPLE_STAGES = [
  {
    id: "A1-1",
    cefr: "A1",
    num: 1,
    name: "ברכות ובסיס",
    nameEn: "Greetings & Basics",
    icon: "👋",
    color: "#58cc02",
    level: "A1",
    wordCount: 50,
    words: [
      {it: "ciao", en: "hello / goodbye", he: "שלום / היי", cat: "greeting"},
      {it: "buongiorno", en: "good morning", he: "בוקר טוב", cat: "greeting"},
      {it: "buonasera", en: "good evening", he: "ערב טוב", cat: "greeting"},
      {it: "buonanotte", en: "good night", he: "לילה טוב", cat: "greeting"},
      {it: "arrivederci", en: "goodbye (formal)", he: "להתראות (רשמי)", cat: "greeting"},
      {it: "grazie", en: "thank you", he: "תודה", cat: "politeness"},
      {it: "prego", en: "you're welcome", he: "בבקשה", cat: "politeness"},
      {it: "per favore", en: "please", he: "בבקשה", cat: "politeness"},
      {it: "scusi", en: "excuse me (formal)", he: "סליחה (רשמי)", cat: "politeness"},
      {it: "scusa", en: "excuse me (informal)", he: "סליחה (לא רשמי)", cat: "politeness"},
      {it: "sì", en: "yes", he: "כן", cat: "basic"},
      {it: "no", en: "no", he: "לא", cat: "basic"},
      {it: "mi chiamo", en: "my name is", he: "קוראים לי", cat: "introduction"},
      {it: "piacere", en: "nice to meet you", he: "נעים מאוד", cat: "introduction"},
      {it: "come stai?", en: "how are you? (informal)", he: "מה שלומך? (לא רשמי)", cat: "greeting"},
      {it: "bene", en: "well / good", he: "טוב", cat: "feeling"},
      {it: "male", en: "badly / bad", he: "רע", cat: "feeling"},
      {it: "così così", en: "so-so", he: "ככה ככה", cat: "feeling"},
      {it: "e tu?", en: "and you? (informal)", he: "ואת/ה?", cat: "greeting"},
      {it: "grazie mille", en: "thank you very much", he: "תודה רבה", cat: "politeness"},
      {it: "di niente", en: "you're welcome / it's nothing", he: "אין בעד מה", cat: "politeness"},
      {it: "va bene", en: "okay / alright", he: "בסדר", cat: "agreement"},
      {it: "ok", en: "okay", he: "אוקיי", cat: "agreement"},
      {it: "pronto", en: "hello (on phone)", he: "הלו (בטלפון)", cat: "phone"},
      {it: "ci vediamo", en: "see you", he: "נתראה", cat: "farewell"},
      {it: "a presto", en: "see you soon", he: "להתראות בקרוב", cat: "farewell"},
      {it: "a dopo", en: "see you later", he: "נתראה אחר כך", cat: "farewell"},
      {it: "a domani", en: "see you tomorrow", he: "נתראה מחר", cat: "farewell"},
      {it: "permesso", en: "excuse me (passing through)", he: "סליחה (מעבר)", cat: "politeness"},
      {it: "salve", en: "hello (formal)", he: "שלום (רשמי)", cat: "greeting"},
      {it: "ecco", en: "here is / here are", he: "הנה", cat: "basic"},
      {it: "allora", en: "so / well then", he: "אז", cat: "basic"},
      {it: "magari", en: "maybe / if only", he: "אולי / הלוואי", cat: "expression"},
      {it: "purtroppo", en: "unfortunately", he: "לרוע המזל", cat: "expression"},
      {it: "certo", en: "of course / certainly", he: "בוודאי", cat: "agreement"},
      {it: "forse", en: "maybe / perhaps", he: "אולי", cat: "uncertainty"},
      {it: "niente", en: "nothing", he: "כלום", cat: "quantity"},
      {it: "qualcosa", en: "something", he: "משהו", cat: "quantity"},
      {it: "tutto", en: "everything / all", he: "הכל", cat: "quantity"},
      {it: "molto", en: "very / much / a lot", he: "מאוד / הרבה", cat: "quantity"},
      {it: "poco", en: "little / few", he: "קצת / מעט", cat: "quantity"},
      {it: "basta", en: "enough / stop", he: "די / מספיק", cat: "expression"},
      {it: "bravo", en: "well done / good job", he: "כל הכבוד", cat: "compliment"},
      {it: "perfetto", en: "perfect", he: "מושלם", cat: "compliment"},
      {it: "giusto", en: "correct / right", he: "נכון", cat: "judgment"},
      {it: "sbagliato", en: "wrong / incorrect", he: "לא נכון / שגוי", cat: "judgment"},
      {it: "uguale", en: "same / equal", he: "אותו הדבר / שווה", cat: "comparison"},
      {it: "diverso", en: "different", he: "שונה", cat: "comparison"},
      {it: "vero", en: "true", he: "אמת / נכון", cat: "judgment"},
      {it: "falso", en: "false", he: "שקר / לא נכון", cat: "judgment"}
    ]
  },
  {
    id: "A1-2",
    cefr: "A1",
    num: 2,
    name: "מספרים וצבעים",
    nameEn: "Numbers & Colors",
    icon: "🔢",
    color: "#ff9600",
    level: "A1",
    wordCount: 50,
    words: [
      {it: "zero", en: "zero", he: "אפס", cat: "number"},
      {it: "uno", en: "one", he: "אחת / אחד", cat: "number"},
      {it: "due", en: "two", he: "שתיים / שניים", cat: "number"},
      {it: "tre", en: "three", he: "שלוש / שלושה", cat: "number"},
      {it: "quattro", en: "four", he: "ארבע / ארבעה", cat: "number"},
      {it: "cinque", en: "five", he: "חמש / חמישה", cat: "number"},
      {it: "sei", en: "six", he: "שש / שישה", cat: "number"},
      {it: "sette", en: "seven", he: "שבע / שבעה", cat: "number"},
      {it: "otto", en: "eight", he: "שמונה", cat: "number"},
      {it: "nove", en: "nine", he: "תשע / תשעה", cat: "number"},
      {it: "dieci", en: "ten", he: "עשר / עשרה", cat: "number"},
      {it: "undici", en: "eleven", he: "אחת עשרה / אחד עשר", cat: "number"},
      {it: "dodici", en: "twelve", he: "שתים עשרה / שנים עשר", cat: "number"},
      {it: "tredici", en: "thirteen", he: "שלוש עשרה / שלושה עשר", cat: "number"},
      {it: "quattordici", en: "fourteen", he: "ארבע עשרה / ארבעה עשר", cat: "number"},
      {it: "quindici", en: "fifteen", he: "חמש עשרה / חמישה עשר", cat: "number"},
      {it: "sedici", en: "sixteen", he: "שש עשרה / שישה עשר", cat: "number"},
      {it: "diciassette", en: "seventeen", he: "שבע עשרה / שבעה עשר", cat: "number"},
      {it: "diciotto", en: "eighteen", he: "שמונה עשרה", cat: "number"},
      {it: "diciannove", en: "nineteen", he: "תשע עשרה / תשעה עשר", cat: "number"},
      {it: "venti", en: "twenty", he: "עשרים", cat: "number"},
      {it: "trenta", en: "thirty", he: "שלושים", cat: "number"},
      {it: "quaranta", en: "forty", he: "ארבעים", cat: "number"},
      {it: "cinquanta", en: "fifty", he: "חמישים", cat: "number"},
      {it: "sessanta", en: "sixty", he: "שישים", cat: "number"},
      {it: "settanta", en: "seventy", he: "שבעים", cat: "number"},
      {it: "ottanta", en: "eighty", he: "שמונים", cat: "number"},
      {it: "novanta", en: "ninety", he: "תשעים", cat: "number"},
      {it: "cento", en: "one hundred", he: "מאה", cat: "number"},
      {it: "mille", en: "one thousand", he: "אלף", cat: "number"},
      {it: "rosso", en: "red", he: "אדום", cat: "color"},
      {it: "blu", en: "blue", he: "כחול", cat: "color"},
      {it: "azzurro", en: "light blue / sky blue", he: "תכלת", cat: "color"},
      {it: "verde", en: "green", he: "ירוק", cat: "color"},
      {it: "giallo", en: "yellow", he: "צהוב", cat: "color"},
      {it: "bianco", en: "white", he: "לבן", cat: "color"},
      {it: "nero", en: "black", he: "שחור", cat: "color"},
      {it: "grigio", en: "gray", he: "אפור", cat: "color"},
      {it: "marrone", en: "brown", he: "חום", cat: "color"},
      {it: "viola", en: "purple", he: "סגול", cat: "color"},
      {it: "arancione", en: "orange", he: "כתום", cat: "color"},
      {it: "rosa", en: "pink", he: "ורוד", cat: "color"},
      {it: "oro", en: "gold", he: "זהב", cat: "color"},
      {it: "argento", en: "silver", he: "כסף", cat: "color"},
      {it: "cerchio", en: "circle", he: "עיגול", cat: "shape"},
      {it: "quadrato", en: "square", he: "ריבוע", cat: "shape"},
      {it: "triangolo", en: "triangle", he: "משולש", cat: "shape"},
      {it: "rettangolo", en: "rectangle", he: "מלבן", cat: "shape"},
      {it: "stella", en: "star", he: "כוכב", cat: "shape"},
      {it: "cuore", en: "heart", he: "לב", cat: "shape"}
    ]
  },
  {
    id: "A1-3",
    cefr: "A1",
    num: 3,
    name: "משפחה ואנשים",
    nameEn: "Family & People",
    icon: "👨‍👩‍👧‍👦",
    color: "#ce82ff",
    level: "A1",
    wordCount: 50,
    words: [
      {it: "madre", en: "mother", he: "אמא", cat: "family"},
      {it: "padre", en: "father", he: "אבא", cat: "family"},
      {it: "fratello", en: "brother", he: "אח", cat: "family"},
      {it: "sorella", en: "sister", he: "אחות", cat: "family"},
      {it: "figlio", en: "son", he: "בן", cat: "family"},
      {it: "figlia", en: "daughter", he: "בת", cat: "family"},
      {it: "marito", en: "husband", he: "בעל", cat: "family"},
      {it: "moglie", en: "wife", he: "אישה", cat: "family"},
      {it: "nonno", en: "grandfather", he: "סבא", cat: "family"},
      {it: "nonna", en: "grandmother", he: "סבתא", cat: "family"},
      {it: "zio", en: "uncle", he: "דוד", cat: "family"},
      {it: "zia", en: "aunt", he: "דודה", cat: "family"},
      {it: "cugino", en: "male cousin", he: "בן דוד", cat: "family"},
      {it: "cugina", en: "female cousin", he: "בת דודה", cat: "family"},
      {it: "bambino", en: "little boy / child", he: "ילד קטן", cat: "people"},
      {it: "bambina", en: "little girl", he: "ילדה קטנה", cat: "people"},
      {it: "ragazzo", en: "boy / young man", he: "ילד / בחור", cat: "people"},
      {it: "ragazza", en: "girl / young woman", he: "ילדה / בחורה", cat: "people"},
      {it: "uomo", en: "man", he: "גבר", cat: "people"},
      {it: "donna", en: "woman", he: "אישה", cat: "people"},
      {it: "amico", en: "friend (male)", he: "חבר", cat: "relationship"},
      {it: "amica", en: "friend (female)", he: "חברה", cat: "relationship"},
      {it: "vicino", en: "neighbor", he: "שכן", cat: "community"},
      {it: "persona", en: "person", he: "אדם / איש", cat: "people"},
      {it: "gente", en: "people", he: "אנשים", cat: "people"},
      {it: "famiglia", en: "family", he: "משפחה", cat: "family"},
      {it: "coppia", en: "couple", he: "זוג", cat: "relationship"},
      {it: "genitori", en: "parents", he: "הורים", cat: "family"},
      {it: "bambini", en: "children", he: "ילדים", cat: "people"},
      {it: "fidanzato", en: "fiancé / boyfriend", he: "ארוס / חבר", cat: "relationship"},
      {it: "fidanzata", en: "fiancée / girlfriend", he: "ארוסה / חברה", cat: "relationship"},
      {it: "signore", en: "gentleman / Mr.", he: "אדון / גבר", cat: "politeness"},
      {it: "signora", en: "lady / Mrs.", he: "גברת", cat: "politeness"},
      {it: "giovane", en: "young", he: "צעיר", cat: "people"},
      {it: "anziano", en: "elderly", he: "קשיש / מבוגר", cat: "people"},
      {it: "adulto", en: "adult", he: "מבוגר", cat: "people"},
      {it: "neonato", en: "newborn baby", he: "תינוק שזה עתה נולד", cat: "people"},
      {it: "nipote", en: "grandchild / nephew / niece", he: "נכד / אחיין / אחיינית", cat: "family"},
      {it: "studente", en: "student", he: "סטודנט / תלמיד", cat: "occupation"},
      {it: "insegnante", en: "teacher", he: "מורה", cat: "occupation"},
      {it: "dottore", en: "doctor", he: "רופא", cat: "occupation"},
      {it: "infermiere", en: "nurse", he: "אחות (רפואית)", cat: "occupation"},
      {it: "poliziotto", en: "police officer", he: "שוטר", cat: "occupation"},
      {it: "cuoco", en: "cook / chef", he: "טבח", cat: "occupation"},
      {it: "artista", en: "artist", he: "אמן", cat: "occupation"},
      {it: "cantante", en: "singer", he: "זמר", cat: "occupation"},
      {it: "attore", en: "actor", he: "שחקן", cat: "occupation"},
      {it: "collega", en: "colleague", he: "עמית לעבודה", cat: "occupation"},
      {it: "capo", en: "boss / chief", he: "בוס / ראש", cat: "occupation"},
      {it: "vicino di casa", en: "next-door neighbor", he: "שכן מדלת לדלת", cat: "community"}
    ]
  },
  {
    id: "A1-4",
    cefr: "A1",
    num: 4,
    name: "אוכל ושתייה",
    nameEn: "Food & Drink",
    icon: "🍝",
    color: "#ff4b4b",
    level: "A1",
    wordCount: 50,
    words: [
      {it: "pane", en: "bread", he: "לחם", cat: "food"},
      {it: "acqua", en: "water", he: "מים", cat: "drink"},
      {it: "vino", en: "wine", he: "יין", cat: "drink"},
      {it: "birra", en: "beer", he: "בירה", cat: "drink"},
      {it: "latte", en: "milk", he: "חלב", cat: "drink"},
      {it: "caffè", en: "coffee", he: "קפה", cat: "drink"},
      {it: "tè", en: "tea", he: "תה", cat: "drink"},
      {it: "zucchero", en: "sugar", he: "סוכר", cat: "condiment"},
      {it: "sale", en: "salt", he: "מלח", cat: "condiment"},
      {it: "olio", en: "oil", he: "שמן", cat: "condiment"},
      {it: "aceto", en: "vinegar", he: "חומץ", cat: "condiment"},
      {it: "pasta", en: "pasta", he: "פסטה", cat: "food"},
      {it: "pizza", en: "pizza", he: "פיצה", cat: "food"},
      {it: "riso", en: "rice", he: "אורז", cat: "food"},
      {it: "formaggio", en: "cheese", he: "גבינה", cat: "food"},
      {it: "prosciutto", en: "ham", he: "חזיר / פרושוטו", cat: "food"},
      {it: "frutta", en: "fruit", he: "פירות", cat: "food"},
      {it: "verdura", en: "vegetables", he: "ירקות", cat: "food"},
      {it: "mela", en: "apple", he: "תפוח", cat: "fruit"},
      {it: "banana", en: "banana", he: "בננה", cat: "fruit"},
      {it: "arancia", en: "orange", he: "תפוז", cat: "fruit"},
      {it: "limone", en: "lemon", he: "לימון", cat: "fruit"},
      {it: "fragola", en: "strawberry", he: "תות", cat: "fruit"},
      {it: "uva", en: "grape / grapes", he: "ענבים", cat: "fruit"},
      {it: "pesca", en: "peach", he: "אפרסק", cat: "fruit"},
      {it: "pesce", en: "fish", he: "דג", cat: "food"},
      {it: "carne", en: "meat", he: "בשר", cat: "food"},
      {it: "pollo", en: "chicken", he: "עוף", cat: "food"},
      {it: "manzo", en: "beef", he: "בקר", cat: "food"},
      {it: "uovo", en: "egg", he: "ביצה", cat: "food"},
      {it: "burro", en: "butter", he: "חמאה", cat: "food"},
      {it: "marmellata", en: "jam / marmalade", he: "ריבה", cat: "food"},
      {it: "miele", en: "honey", he: "דבש", cat: "food"},
      {it: "cioccolato", en: "chocolate", he: "שוקולד", cat: "food"},
      {it: "torta", en: "cake", he: "עוגה", cat: "food"},
      {it: "biscotto", en: "cookie / biscuit", he: "עוגייה", cat: "food"},
      {it: "minestra", en: "soup", he: "מרק", cat: "food"},
      {it: "insalata", en: "salad", he: "סלט", cat: "food"},
      {it: "patata", en: "potato", he: "תפוח אדמה", cat: "vegetable"},
      {it: "carota", en: "carrot", he: "גזר", cat: "vegetable"},
      {it: "cipolla", en: "onion", he: "בצל", cat: "vegetable"},
      {it: "aglio", en: "garlic", he: "שום", cat: "vegetable"},
      {it: "pomodoro", en: "tomato", he: "עגבנייה", cat: "vegetable"},
      {it: "funghi", en: "mushrooms", he: "פטריות", cat: "vegetable"},
      {it: "panino", en: "sandwich / bread roll", he: "כריך / לחמנייה", cat: "food"},
      {it: "pranzo", en: "lunch", he: "ארוחת צהריים", cat: "meal"},
      {it: "cena", en: "dinner", he: "ארוחת ערב", cat: "meal"},
      {it: "colazione", en: "breakfast", he: "ארוחת בוקר", cat: "meal"},
      {it: "merenda", en: "snack (afternoon)", he: "חטיף / ארוחת ביניים", cat: "meal"},
      {it: "fame", en: "hunger", he: "רעב", cat: "sensation"}
    ]
  },
  {
    id: "A1-5",
    cefr: "A1",
    num: 5,
    name: "חפצים יומיומיים ובית",
    nameEn: "Daily Objects & Home",
    icon: "🏠",
    color: "#1cb0f6",
    level: "A1",
    wordCount: 50,
    words: [
      {it: "casa", en: "house / home", he: "בית", cat: "home"},
      {it: "stanza", en: "room", he: "חדר", cat: "home"},
      {it: "camera da letto", en: "bedroom", he: "חדר שינה", cat: "home"},
      {it: "cucina", en: "kitchen", he: "מטבח", cat: "home"},
      {it: "bagno", en: "bathroom", he: "שירותים / אמבטיה", cat: "home"},
      {it: "sala da pranzo", en: "dining room", he: "חדר אוכל", cat: "home"},
      {it: "letto", en: "bed", he: "מיטה", cat: "furniture"},
      {it: "tavolo", en: "table", he: "שולחן", cat: "furniture"},
      {it: "sedia", en: "chair", he: "כיסא", cat: "furniture"},
      {it: "armadio", en: "wardrobe / closet", he: "ארון בגדים", cat: "furniture"},
      {it: "porta", en: "door", he: "דלת", cat: "home"},
      {it: "finestra", en: "window", he: "חלון", cat: "home"},
      {it: "specchio", en: "mirror", he: "מראה", cat: "home"},
      {it: "luce", en: "light", he: "אור", cat: "home"},
      {it: "lampada", en: "lamp", he: "מנורה", cat: "furniture"},
      {it: "telefono", en: "telephone", he: "טלפון", cat: "technology"},
      {it: "computer", en: "computer", he: "מחשב", cat: "technology"},
      {it: "televisione", en: "television", he: "טלוויזיה", cat: "technology"},
      {it: "libro", en: "book", he: "ספר", cat: "object"},
      {it: "penna", en: "pen", he: "עט", cat: "object"},
      {it: "foglio", en: "sheet of paper", he: "דף", cat: "object"},
      {it: "scrivania", en: "desk", he: "שולחן עבודה", cat: "furniture"},
      {it: "scaffale", en: "shelf / bookshelf", he: "מדף", cat: "furniture"},
      {it: "divano", en: "sofa / couch", he: "ספה", cat: "furniture"},
      {it: "tende", en: "curtains", he: "וילונות", cat: "home"},
      {it: "tappeto", en: "carpet / rug", he: "שטיח", cat: "home"},
      {it: "cuscino", en: "pillow / cushion", he: "כרית", cat: "home"},
      {it: "coperta", en: "blanket", he: "שמיכה", cat: "home"},
      {it: "asciugamano", en: "towel", he: "מגבת", cat: "bathroom"},
      {it: "sapone", en: "soap", he: "סבון", cat: "bathroom"},
      {it: "dentifricio", en: "toothpaste", he: "משחת שיניים", cat: "bathroom"},
      {it: "spazzolino", en: "toothbrush", he: "מברשת שיניים", cat: "bathroom"},
      {it: "pettine", en: "comb", he: "מסרק", cat: "bathroom"},
      {it: "chiave", en: "key", he: "מפתח", cat: "object"},
      {it: "orologio", en: "watch / clock", he: "שעון", cat: "object"},
      {it: "calendario", en: "calendar", he: "לוח שנה", cat: "object"},
      {it: "foto", en: "photo / picture", he: "תמונה (צילום)", cat: "object"},
      {it: "quadro", en: "painting / picture", he: "ציור / תמונה", cat: "object"},
      {it: "vaso", en: "vase", he: "אגרטל", cat: "object"},
      {it: "pianta", en: "plant", he: "צמח", cat: "object"},
      {it: "borsa", en: "bag / purse", he: "תיק", cat: "accessory"},
      {it: "vestito", en: "dress / clothing", he: "שמלה / בגד", cat: "clothing"},
      {it: "scarpe", en: "shoes", he: "נעליים", cat: "clothing"},
      {it: "cappotto", en: "coat / overcoat", he: "מעיל", cat: "clothing"},
      {it: "ombrello", en: "umbrella", he: "מטרייה", cat: "accessory"},
      {it: "soldi", en: "money", he: "כסף", cat: "object"},
      {it: "portafoglio", en: "wallet", he: "ארנק", cat: "accessory"},
      {it: "occhiali", en: "glasses / spectacles", he: "משקפיים", cat: "accessory"},
      {it: "cellulare", en: "mobile phone", he: "טלפון נייד", cat: "technology"},
      {it: "caricatore", en: "charger", he: "מטען", cat: "technology"}
    ]
  }
];
const SITUATIONS = [
  {
    id: "sit-ristorante",
    name: "במסעדה",
    nameEn: "At the Restaurant",
    icon: "🍕",
    color: "#ff9600",
    words: [
      {it: "il cameriere", he: "המלצר"},
      {it: "il menu", he: "התפריט"},
      {it: "la forchetta", he: "המזלג"},
      {it: "il coltello", he: "הסכין"},
      {it: "il cucchiaio", he: "הכף"},
      {it: "il piatto", he: "הצלחת"},
      {it: "il bicchiere", he: "הכוס"},
      {it: "il tavolo", he: "השולחן"},
      {it: "il conto", he: "החשבון"},
      {it: "la mancia", he: "הטיפ"},
      {it: "l'antipasto", he: "המתאבן"},
      {it: "il dolce", he: "הקינוח"}
    ],
    phrases: [
      {it: "Vorrei ordinare...", he: "הייתי רוצה להזמין..."},
      {it: "Il conto, per favore", he: "החשבון, בבקשה"},
      {it: "Posso vedere il menu?", he: "אפשר לראות את התפריט?"},
      {it: "Raccomando questo piatto", he: "אני ממליץ על המנה הזו"},
      {it: "Salute! Cin cin!", he: "לחיים!"},
      {it: "Era delizioso", he: "זה היה טעים"},
      {it: "Un tavolo per due, per favore", he: "שולחן לשניים, בבקשה"},
      {it: "Cosa desidera da bere?", he: "מה תרצה לשתות?"}
    ]
  },
  {
    id: "sit-supermercato",
    name: "בסופרמרקט",
    nameEn: "At the Supermarket",
    icon: "🛒",
    color: "#22c55e",
    words: [
      {it: "il carrello", he: "עגלת הקניות"},
      {it: "il cestino", he: "הסל"},
      {it: "il pane", he: "הלחם"},
      {it: "il latte", he: "החלב"},
      {it: "le uova", he: "הביצים"},
      {it: "il formaggio", he: "הגבינה"},
      {it: "la frutta", he: "הפירות"},
      {it: "la verdura", he: "הירקות"},
      {it: "il cassiere", he: "הקופאי"},
      {it: "lo scontrino", he: "הקבלה"},
      {it: "la busta", he: "השקית"},
      {it: "il prezzo", he: "המחיר"}
    ],
    phrases: [
      {it: "Quanto costa questo?", he: "כמה זה עולה?"},
      {it: "Cerco...", he: "אני מחפש..."},
      {it: "Avete...?", he: "יש לכם...?"},
      {it: "Posso pagare con la carta?", he: "אפשר לשלם בכרטיס?"},
      {it: "Ho bisogno di una busta", he: "אני צריך שקית"},
      {it: "Dov'è...?", he: "איפה נמצא...?"},
      {it: "Questo è in offerta?", he: "זה במבצע?"},
      {it: "Prendo questo", he: "אני אקח את זה"}
    ]
  },
  {
    id: "sit-aeroporto",
    name: "בשדה התעופה",
    nameEn: "At the Airport",
    icon: "✈️",
    color: "#3b82f6",
    words: [
      {it: "l'aeroporto", he: "שדה התעופה"},
      {it: "il volo", he: "הטיסה"},
      {it: "il biglietto", he: "הכרטיס"},
      {it: "il passaporto", he: "הדרכון"},
      {it: "la carta d'imbarco", he: "כרטיס העלייה למטוס"},
      {it: "la valigia", he: "המזוודה"},
      {it: "il check-in", he: "הצ'ק-אין"},
      {it: "il gate", he: "שער העלייה"},
      {it: "la partenza", he: "היציאה"},
      {it: "l'arrivo", he: "ההגעה"},
      {it: "il ritardo", he: "העיכוב"},
      {it: "la cintura di sicurezza", he: "חגורת הבטיחות"}
    ],
    phrases: [
      {it: "Dov'è il banco del check-in?", he: "איפה דלפק הצ'ק-אין?"},
      {it: "Posso vedere il suo passaporto?", he: "אפשר לראות את הדרכון שלך?"},
      {it: "A quale gate è il mio volo?", he: "באיזה שער הטיסה שלי?"},
      {it: "Quante valigie ha?", he: "כמה מזוודות יש לך?"},
      {it: "Il volo è in ritardo", he: "הטיסה מתעכבת"},
      {it: "Imbarco ora", he: "עכשיו עלייה למטוס"},
      {it: "Buon viaggio!", he: "טיסה נעימה!"},
      {it: "Dov'è il ritiro bagagli?", he: "איפה איסוף המזוודות?"}
    ]
  },
  {
    id: "sit-hotel",
    name: "במלון",
    nameEn: "At the Hotel",
    icon: "🏨",
    color: "#a855f7",
    words: [
      {it: "l'hotel", he: "המלון"},
      {it: "la camera", he: "החדר"},
      {it: "la reception", he: "קבלת הפנים"},
      {it: "la chiave elettronica", he: "כרטיס המפתח"},
      {it: "la prenotazione", he: "ההזמנה"},
      {it: "la camera singola", he: "חדר יחיד"},
      {it: "la camera doppia", he: "חדר זוגי"},
      {it: "la colazione", he: "ארוחת הבוקר"},
      {it: "la piscina", he: "הבריכה"},
      {it: "il parcheggio", he: "החנייה"},
      {it: "il check-out", he: "הצ'ק-אאוט"},
      {it: "la password wifi", he: "סיסמת הווייפיי"}
    ],
    phrases: [
      {it: "Ho una prenotazione", he: "יש לי הזמנה"},
      {it: "Qual è la password del wifi?", he: "מה סיסמת הווייפיי?"},
      {it: "La colazione è inclusa?", he: "ארוחת הבוקר כלולה?"},
      {it: "Posso fare il check-out più tardi?", he: "אפשר לעשות צ'ק-אאוט מאוחר יותר?"},
      {it: "La chiave della camera, per favore", he: "מפתח החדר, בבקשה"},
      {it: "Servizio in camera!", he: "שירות חדרים!"},
      {it: "C'è il parcheggio?", he: "יש חנייה?"},
      {it: "L'aria condizionata non funziona", he: "המזגן לא עובד"}
    ]
  },
  {
    id: "sit-shopping",
    name: "קניות",
    nameEn: "Shopping",
    icon: "👕",
    color: "#ec4899",
    words: [
      {it: "il negozio", he: "החנות"},
      {it: "la taglia", he: "המידה"},
      {it: "il colore", he: "הצבע"},
      {it: "il camerino", he: "תא ההלבשה"},
      {it: "lo specchio", he: "המראה"},
      {it: "il cartellino del prezzo", he: "תג המחיר"},
      {it: "lo sconto", he: "ההנחה"},
      {it: "la cassa", he: "הקופה"},
      {it: "il rimborso", he: "ההחזר"},
      {it: "la carta di credito", he: "כרטיס האשראי"},
      {it: "i contanti", he: "המזומן"},
      {it: "il resto", he: "העודף"}
    ],
    phrases: [
      {it: "Posso provarlo?", he: "אפשר למדוד?"},
      {it: "Che taglia è questa?", he: "איזו מידה זו?"},
      {it: "Quanto costa?", he: "כמה זה עולה?"},
      {it: "Avete questo in un altro colore?", he: "יש את זה בצבע אחר?"},
      {it: "C'è uno sconto?", he: "יש הנחה?"},
      {it: "Lo prendo", he: "אני אקח את זה"},
      {it: "Sto solo guardando", he: "רק מסתכל"},
      {it: "Posso restituirlo?", he: "אפשר להחזיר?"}
    ]
  },
  {
    id: "sit-dottore",
    name: "אצל הרופא",
    nameEn: "At the Doctor",
    icon: "🏥",
    color: "#ef4444",
    words: [
      {it: "il dottore", he: "הרופא"},
      {it: "l'infermiere", he: "האחות"},
      {it: "l'ospedale", he: "בית החולים"},
      {it: "la farmacia", he: "בית המרקחת"},
      {it: "la medicina", he: "התרופה"},
      {it: "la ricetta", he: "המרשם"},
      {it: "la febbre", he: "החום"},
      {it: "la tosse", he: "השיעול"},
      {it: "il mal di testa", he: "כאב הראש"},
      {it: "il raffreddore", he: "הצטננות"},
      {it: "il dolore", he: "הכאב"},
      {it: "l'appuntamento", he: "התור"}
    ],
    phrases: [
      {it: "Non mi sento bene", he: "אני לא מרגיש טוב"},
      {it: "Dove fa male?", he: "איפה כואב?"},
      {it: "Ho la febbre", he: "יש לי חום"},
      {it: "Ha un'assicurazione?", he: "יש לך ביטוח?"},
      {it: "Ho bisogno di un dottore", he: "אני צריך רופא"},
      {it: "Prenda questa medicina", he: "קח את התרופה הזו"},
      {it: "Rimanga a letto", he: "תישאר במיטה"},
      {it: "Torni la settimana prossima", he: "תחזור בשבוע הבא"}
    ]
  }
];
const CONVERSATIONS = [
  {
    id: "conv-ordine",
    name: "להזמין קפה",
    nameEn: "Ordering Coffee",
    icon: "☕",
    lines: [
      {speaker: "A", it: "Buongiorno!", he: "בוקר טוב!"},
      {speaker: "B", it: "Buongiorno! Cosa desidera?", he: "בוקר טוב! מה תרצה?"},
      {speaker: "A", it: "Un cappuccino, per favore.", he: "קפוצ'ינו, בבקשה."},
      {speaker: "B", it: "Lo vuole piccolo o grande?", he: "אתה רוצה קטן או גדול?"},
      {speaker: "A", it: "Grande, grazie. Quanto costa?", he: "גדול, תודה. כמה זה עולה?"},
      {speaker: "B", it: "4 euro e 50 centesimi.", he: "4 יורו ו-50 סנט."},
      {speaker: "A", it: "Ecco a lei. Posso pagare con la carta?", he: "הנה. אני יכול לשלם בכרטיס?"},
      {speaker: "B", it: "Certo, faccia pure.", he: "בטח, בבקשה."},
      {speaker: "A", it: "Grazie mille, buona giornata!", he: "תודה רבה, יום טוב!"},
      {speaker: "B", it: "Arrivederci, buona giornata!", he: "להתראות, יום טוב!"}
    ]
  },
  {
    id: "conv-conoscere",
    name: "להכיר מישהו",
    nameEn: "Meeting Someone New",
    icon: "🤝",
    lines: [
      {speaker: "A", it: "Ciao! Io sono Marco. Come ti chiami?", he: "שלום! אני מרקו. איך קוראים לך?"},
      {speaker: "B", it: "Ciao Marco! Mi chiamo Sarah.", he: "שלום מרקו! קוראים לי שרה."},
      {speaker: "A", it: "Piacere, Sarah!", he: "נעים מאוד, שרה!"},
      {speaker: "B", it: "Piacere mio! Di dove sei?", he: "גם נעים לי! מאיפה אתה?"},
      {speaker: "A", it: "Sono di Roma. E tu?", he: "אני מרומא. ואת?"},
      {speaker: "B", it: "Sono israeliana, di Tel Aviv.", he: "אני ישראלית, מתל אביב."},
      {speaker: "A", it: "Che bello! Come stai?", he: "נפלא! מה שלומך?"},
      {speaker: "B", it: "Bene, grazie! E tu?", he: "בסדר, תודה! ואתה?"},
      {speaker: "A", it: "Benissimo! È un piacere conoscerti.", he: "מצוין! כיף להכיר אותך."},
      {speaker: "B", it: "Anche per me. A dopo!", he: "גם מבחינתי. נתראה!"}
    ]
  },
  {
    id: "conv-ristorante",
    name: "במסעדה",
    nameEn: "At the Restaurant",
    icon: "🍝",
    lines: [
      {speaker: "A", it: "Buonasera! Vorrei un tavolo per due, per favore.", he: "ערב טוב! הייתי רוצה שולחן לשניים, בבקשה."},
      {speaker: "B", it: "Buonasera! Prego, si accomodi.", he: "ערב טוב! בבקשה, שבו."},
      {speaker: "A", it: "Grazie. Cosa ci consiglia?", he: "תודה. מה אתם ממליצים?"},
      {speaker: "B", it: "La pasta alla carbonara è ottima. E il vino della casa è molto buono.", he: "הפסטה קרבונרה מעולה. והיין של הבית טוב מאוד."},
      {speaker: "A", it: "Allora prendo la carbonara e un bicchiere di vino rosso.", he: "אז אני אקח קרבונרה וכוס יין אדום."},
      {speaker: "B", it: "Ottima scelta! Arriva subito.", he: "בחירה מצוינת! זה מגיע מיד."},
      {speaker: "A", it: "Era delizioso, davvero complimenti!", he: "היה טעים מאוד, כל הכבוד!"},
      {speaker: "B", it: "Grazie mille! Desidera altro?", he: "תודה רבה! תרצה עוד משהו?"},
      {speaker: "A", it: "No grazie, il conto per favore.", he: "לא תודה, את החשבון בבקשה."},
      {speaker: "B", it: "Ecco il conto. Sono 28 euro.", he: "הנה החשבון. 28 יורו."},
      {speaker: "A", it: "Tenga il resto. Arrivederci!", he: "תשמור את העודף. להתראות!"},
      {speaker: "B", it: "Grazie e arrivederci!", he: "תודה ולהתראות!"}
    ]
  },
  {
    id: "conv-abbigliamento",
    name: "לקנות בגדים",
    nameEn: "Shopping for Clothes",
    icon: "👔",
    lines: [
      {speaker: "A", it: "Buongiorno, posso aiutarla?", he: "בוקר טוב, אפשר לעזור לך?"},
      {speaker: "B", it: "Buongiorno! Sto cercando una camicia.", he: "בוקר טוב! אני מחפשת חולצה."},
      {speaker: "A", it: "Che taglia porta?", he: "איזה מידה את לובשת?"},
      {speaker: "B", it: "Porto la taglia M. Posso provarla?", he: "אני לובשת מידה M. אפשר למדוד?"},
      {speaker: "A", it: "Certo, il camerino è là.", he: "בטח, תא ההלבשה שם."},
      {speaker: "B", it: "Mi piace molto. Quanto costa?", he: "אני מאוד אוהבת. כמה זה עולה?"},
      {speaker: "A", it: "39 euro. È in sconto questa settimana.", he: "39 יורו. זה בהנחה השבוע."},
      {speaker: "B", it: "Perfetto, lo prendo. C'è anche in blu?", he: "מושלם, אני לוקחת. יש גם בכחול?"},
      {speaker: "A", it: "Sì, eccolo in blu.", he: "כן, הנה זה בכחול."},
      {speaker: "B", it: "Lo prendo in blu. Ecco la carta.", he: "אני לוקחת בכחול. הנה הכרטיס."}
    ]
  },
  {
    id: "conv-direzioni",
    name: "לשאול על הכיוונים",
    nameEn: "Asking for Directions",
    icon: "🗺️",
    lines: [
      {speaker: "A", it: "Scusi, mi può aiutare?", he: "סלח לי, אתה יכול לעזור לי?"},
      {speaker: "B", it: "Certo, mi dica.", he: "בטח, תגיד לי."},
      {speaker: "A", it: "Dov'è la stazione dei treni, per favore?", he: "איפה תחנת הרכבת, בבקשה?"},
      {speaker: "B", it: "È abbastanza vicina. Vada sempre diritto.", he: "היא די קרובה. לך ישר."},
      {speaker: "A", it: "Sempre diritto? Poi giro?", he: "ישר? אחר כך אני פונה?"},
      {speaker: "B", it: "Poi gira a sinistra al semaforo.", he: "אחר כך תפנה שמאלה ברמזור."},
      {speaker: "A", it: "A sinistra al semaforo. E dopo?", he: "שמאלה ברמזור. ואז?"},
      {speaker: "B", it: "Dopo 100 metri, la stazione è sulla destra.", he: "אחרי 100 מטר, התחנה בצד ימין."},
      {speaker: "A", it: "Perfetto, grazie mille!", he: "מושלם, תודה רבה!"},
      {speaker: "B", it: "Di niente. Buona giornata!", he: "בבקשה. יום טוב!"}
    ]
  },
  {
    id: "conv-medico",
    name: "ברופא",
    nameEn: "At the Doctor",
    icon: "🏥",
    lines: [
      {speaker: "A", it: "Buongiorno, dottore. Non mi sento bene.", he: "בוקר טוב, דוקטור. אני לא מרגיש טוב."},
      {speaker: "B", it: "Buongiorno. Da quanto tempo si sente così?", he: "בוקר טוב. ממתי אתה מרגיש ככה?"},
      {speaker: "A", it: "Da due giorni. Ho mal di testa e ho la febbre.", he: "יומיים. יש לי כאב ראש ויש לי חום."},
      {speaker: "B", it: "Misuriamo la febbre. 38 e mezzo. È un po' alta.", he: "נמדוד חום. 38 וחצי. זה קצת גבוה."},
      {speaker: "A", it: "Cosa devo fare, dottore?", he: "מה אני צריך לעשות, דוקטור?"},
      {speaker: "B", it: "Prenda questa medicina due volte al giorno.", he: "קח את התרופה הזאת פעמיים ביום."},
      {speaker: "A", it: "Va bene. Devo restare a casa?", he: "בסדר. אני צריך להישאר בבית?"},
      {speaker: "B", it: "Sì, riposi e beva molta acqua.", he: "כן, תנוח ותשתה הרבה מים."},
      {speaker: "A", it: "Grazie, dottore. Quando devo tornare?", he: "תודה, דוקטור. מתי אני צריך לחזור?"},
      {speaker: "B", it: "Torni la settimana prossima se non passa.", he: "תחזור בשבוע הבא אם זה לא עובר."},
      {speaker: "A", it: "Va bene. Arrivederci e grazie.", he: "בסדר. להתראות ותודה."},
      {speaker: "B", it: "Arrivederci e si prenda cura di sé!", he: "להתראות ותשמור על עצמך!"}
    ]
  }
];

// ═══ Apply simple stage overrides ═══
(function patchSimpleStages() {
  var ids = SIMPLE_STAGES.map(function(s) { return s.id; });
  for (var i = 0; i < STAGES.length; i++) {
    var idx = ids.indexOf(STAGES[i].id);
    if (idx !== -1) {
      STAGES[i].name = SIMPLE_STAGES[idx].name;
      STAGES[i].nameEn = SIMPLE_STAGES[idx].nameEn;
      STAGES[i].icon = SIMPLE_STAGES[idx].icon;
      STAGES[i].color = SIMPLE_STAGES[idx].color;
      STAGES[i].words = SIMPLE_STAGES[idx].words;
      STAGES[i].wordCount = SIMPLE_STAGES[idx].wordCount;
    }
  }
})();
