// VolaLingo - 1000 Most Common Italian Words
// Generated from "1000 most common words in Italian - Strømmen Languages"
// Levels: A1 (1-200), A2 (201-400), B1 (401-600), B2 (601-800), C1 (801-1000)

const WORDS = [
  {it:"sono",en:"I am",he:"אני",level:"A1",cat:"pronouns",num:1},
  {it:"io",en:"I",he:"אני",level:"A1",cat:"pronouns",num:2},
  {it:"il suo",en:"his",he:"שלו",level:"A1",cat:"pronouns",num:3},
  {it:"che",en:"that",he:"ש/זה",level:"A1",cat:"grammar",num:4},
  {it:"lui",en:"he",he:"הוא",level:"A1",cat:"pronouns",num:5},
  {it:"era",en:"he/she was",he:"הוא/היא היה",level:"A1",cat:"pronouns",num:6},
  {it:"per",en:"for",he:"בשביל",level:"A1",cat:"grammar",num:7},
  {it:"su",en:"on",he:"על",level:"A1",cat:"grammar",num:8},
  {it:"come",en:"as/like",he:"כמו",level:"A1",cat:"general",num:9},
  {it:"con",en:"with",he:"עם",level:"A1",cat:"grammar",num:10},
  {it:"loro",en:"they",he:"הם",level:"A1",cat:"pronouns",num:11},
  {it:"essere",en:"to be",he:"להיות",level:"A1",cat:"verbs",num:12},
  {it:"a",en:"at",he:"ב",level:"A1",cat:"grammar",num:13},
  {it:"uno",en:"one",he:"אחד",level:"A1",cat:"grammar",num:14},
  {it:"avere",en:"to have",he:"להיות לו",level:"A1",cat:"verbs",num:15},
  {it:"questo",en:"this",he:"זה",level:"A1",cat:"general",num:16},
  {it:"da",en:"from",he:"מ",level:"A1",cat:"grammar",num:17},
  {it:"di",en:"by",he:"על ידי",level:"A1",cat:"grammar",num:18},
  {it:"caldo",en:"hot",he:"חם",level:"A1",cat:"adjectives",num:19},
  {it:"parola",en:"word",he:"מילה",level:"A1",cat:"general",num:20},
  {it:"ma",en:"but",he:"אבל",level:"A1",cat:"grammar",num:21},
  {it:"cosa",en:"what",he:"מה",level:"A1",cat:"clothing",num:22},
  {it:"alcuni",en:"some",he:"כמה",level:"A1",cat:"general",num:23},
  {it:"è",en:"is",he:"הוא",level:"A1",cat:"verbs",num:24},
  {it:"quello",en:"that",he:"ש/זה",level:"A1",cat:"grammar",num:25},
  {it:"voi",en:"you (pl)",he:"אתם",level:"A1",cat:"pronouns",num:26},
  {it:"o",en:"or",he:"או",level:"A1",cat:"grammar",num:27},
  {it:"aveva",en:"had",he:"היה לו",level:"A1",cat:"verbs",num:28},
  {it:"il",en:"the",he:"ה",level:"A1",cat:"grammar",num:29},
  {it:"di",en:"of",he:"של",level:"A1",cat:"grammar",num:30},
  {it:"a",en:"to",he:"ל",level:"A1",cat:"grammar",num:31},
  {it:"e",en:"and",he:"ו",level:"A1",cat:"grammar",num:32},
  {it:"un",en:"a",he:"א",level:"A1",cat:"grammar",num:33},
  {it:"in",en:"in",he:"ב",level:"A1",cat:"grammar",num:34},
  {it:"noi",en:"we",he:"אנחנו",level:"A1",cat:"pronouns",num:35},
  {it:"lattina",en:"can (of soda)",he:"פחית",level:"A1",cat:"general",num:36},
  {it:"fuori",en:"out",he:"החוצה",level:"A1",cat:"adverbs",num:37},
  {it:"altro",en:"other",he:"אחר",level:"A1",cat:"general",num:38},
  {it:"erano",en:"were",he:"היו",level:"A1",cat:"verbs",num:39},
  {it:"che",en:"which",he:"איזה",level:"A1",cat:"grammar",num:40},
  {it:"fare",en:"to do/make",he:"לעשות",level:"A1",cat:"verbs",num:41},
  {it:"loro",en:"their",he:"שלהם",level:"A1",cat:"pronouns",num:42},
  {it:"tempo",en:"time",he:"זמן",level:"A1",cat:"time",num:43},
  {it:"se",en:"if",he:"אם",level:"A1",cat:"grammar",num:44},
  {it:"volontà",en:"will",he:"רצון/עתיד",level:"A1",cat:"general",num:45},
  {it:"come",en:"how",he:"איך",level:"A1",cat:"general",num:46},
  {it:"detto",en:"said",he:"אמר",level:"A1",cat:"general",num:47},
  {it:"un",en:"an",he:"-",level:"A1",cat:"grammar",num:48},
  {it:"ogni",en:"each",he:"כל",level:"A1",cat:"adjectives",num:49},
  {it:"dire",en:"tell",he:"לספר",level:"A1",cat:"verbs",num:50},
  {it:"fa",en:"does",he:"עושה",level:"A1",cat:"general",num:51},
  {it:"fisso",en:"set (unchanging)",he:"קבוע",level:"A1",cat:"general",num:52},
  {it:"tre",en:"three",he:"שלוש",level:"A1",cat:"numbers",num:53},
  {it:"desiderare",en:"desire",he:"לרצות",level:"A1",cat:"verbs",num:54},
  {it:"aria",en:"air",he:"אוויר",level:"A1",cat:"general",num:55},
  {it:"bene",en:"well",he:"טוב",level:"A1",cat:"adverbs",num:56},
  {it:"anche",en:"also",he:"גם",level:"A1",cat:"adverbs",num:57},
  {it:"giocare",en:"play",he:"לשחק",level:"A1",cat:"verbs",num:58},
  {it:"piccolo",en:"small",he:"קטן",level:"A1",cat:"adjectives",num:59},
  {it:"fine",en:"end",he:"סוף",level:"A1",cat:"general",num:60},
  {it:"mettere",en:"put",he:"לשים",level:"A1",cat:"verbs",num:61},
  {it:"casa",en:"home",he:"בית",level:"A1",cat:"places",num:62},
  {it:"leggere",en:"read",he:"לקרוא",level:"A1",cat:"verbs",num:63},
  {it:"mano",en:"hand",he:"יד",level:"A1",cat:"body",num:64},
  {it:"portare",en:"carry",he:"לשאת",level:"A1",cat:"transport",num:65},
  {it:"grande",en:"large",he:"גדול",level:"A1",cat:"adjectives",num:66},
  {it:"compitare",en:"spell (words)",he:"לאיית",level:"A1",cat:"verbs",num:67},
  {it:"aggiungere",en:"add",he:"להוסיף",level:"A1",cat:"verbs",num:68},
  {it:"anche",en:"even/also",he:"גם",level:"A1",cat:"general",num:69},
  {it:"terra",en:"land",he:"ארץ",level:"A1",cat:"general",num:70},
  {it:"qui",en:"here",he:"כאן",level:"A1",cat:"adverbs",num:71},
  {it:"devo",en:"I must",he:"אני חייב",level:"A1",cat:"pronouns",num:72},
  {it:"grande",en:"big",he:"גדול",level:"A1",cat:"adjectives",num:73},
  {it:"alto",en:"high/tall",he:"גבוה",level:"A1",cat:"general",num:74},
  {it:"tale",en:"such",he:"כזה",level:"A1",cat:"general",num:75},
  {it:"seguire",en:"follow",he:"לעקוב",level:"A1",cat:"verbs",num:76},
  {it:"atto",en:"an act",he:"מעשה",level:"A1",cat:"general",num:77},
  {it:"perché",en:"why",he:"למה",level:"A1",cat:"general",num:78},
  {it:"chiedere",en:"ask",he:"לשאול",level:"A1",cat:"verbs",num:79},
  {it:"maschi",en:"men",he:"גברים",level:"A1",cat:"general",num:80},
  {it:"cambiamento",en:"a change",he:"שינוי",level:"A1",cat:"general",num:81},
  {it:"è andato",en:"he/she went",he:"הוא/היא הלך",level:"A1",cat:"pronouns",num:82},
  {it:"luce",en:"light",he:"אור",level:"A1",cat:"adjectives",num:83},
  {it:"tipo",en:"kind (of thing)",he:"סוג",level:"A1",cat:"adjectives",num:84},
  {it:"spento",en:"turned off",he:"כבוי",level:"A1",cat:"general",num:85},
  {it:"bisogno",en:"need",he:"צורך",level:"A1",cat:"general",num:86},
  {it:"casa",en:"house",he:"בית",level:"A1",cat:"places",num:87},
  {it:"immagine",en:"image",he:"תמונה",level:"A1",cat:"general",num:88},
  {it:"provare",en:"try",he:"לנסות",level:"A1",cat:"verbs",num:89},
  {it:"noi",en:"us",he:"אותנו",level:"A1",cat:"pronouns",num:90},
  {it:"di nuovo",en:"again",he:"שוב",level:"A1",cat:"adverbs",num:91},
  {it:"animale",en:"animal",he:"חיה",level:"A1",cat:"general",num:92},
  {it:"punto",en:"point",he:"נקודה",level:"A1",cat:"general",num:93},
  {it:"madre",en:"mother",he:"אמא",level:"A1",cat:"family",num:94},
  {it:"mondo",en:"world",he:"עולם",level:"A1",cat:"general",num:95},
  {it:"vicino",en:"near",he:"קרוב",level:"A1",cat:"body",num:96},
  {it:"costruire",en:"build",he:"לבנות",level:"A1",cat:"verbs",num:97},
  {it:"se stesso",en:"himself",he:"את עצמו",level:"A1",cat:"pronouns",num:98},
  {it:"terra",en:"earth",he:"ארץ",level:"A1",cat:"body",num:99},
  {it:"padre",en:"father",he:"אבא",level:"A1",cat:"family",num:100},
  {it:"qualsiasi",en:"any",he:"כל",level:"A1",cat:"general",num:101},
  {it:"nuovo",en:"new",he:"חדש",level:"A1",cat:"adjectives",num:102},
  {it:"lavoro",en:"work",he:"עבודה",level:"A1",cat:"general",num:103},
  {it:"parte",en:"part",he:"חלק",level:"A1",cat:"general",num:104},
  {it:"prendere",en:"take",he:"לקחת",level:"A1",cat:"verbs",num:105},
  {it:"ottenere",en:"get",he:"להשיג",level:"A1",cat:"verbs",num:106},
  {it:"posto",en:"place",he:"מקום",level:"A1",cat:"general",num:107},
  {it:"fatto",en:"made",he:"עשוי",level:"A1",cat:"general",num:108},
  {it:"vivere",en:"live",he:"לחיות",level:"A1",cat:"verbs",num:109},
  {it:"dove",en:"where",he:"איפה",level:"A1",cat:"grammar",num:110},
  {it:"dopo",en:"after",he:"אחרי",level:"A1",cat:"grammar",num:111},
  {it:"indietro",en:"back",he:"חזרה",level:"A1",cat:"body",num:112},
  {it:"poco",en:"little",he:"קטן",level:"A1",cat:"adjectives",num:113},
  {it:"solo",en:"only",he:"רק",level:"A1",cat:"adverbs",num:114},
  {it:"turno",en:"round",he:"עגול",level:"A1",cat:"adjectives",num:115},
  {it:"uomo",en:"man",he:"איש",level:"A1",cat:"general",num:116},
  {it:"anno",en:"year",he:"שנה",level:"A1",cat:"time",num:117},
  {it:"è venuto",en:"came",he:"הגיע",level:"A1",cat:"verbs",num:118},
  {it:"spettacolo",en:"show",he:"מופע",level:"A1",cat:"general",num:119},
  {it:"ogni",en:"every",he:"כל",level:"A1",cat:"adjectives",num:120},
  {it:"buono",en:"good",he:"טוב",level:"A1",cat:"adjectives",num:121},
  {it:"me",en:"me",he:"אותי",level:"A1",cat:"pronouns",num:122},
  {it:"dare",en:"give",he:"לתת",level:"A1",cat:"verbs",num:123},
  {it:"il nostro",en:"our",he:"שלנו",level:"A1",cat:"pronouns",num:124},
  {it:"sotto",en:"under",he:"מתחת",level:"A1",cat:"grammar",num:125},
  {it:"nome",en:"name",he:"שם",level:"A1",cat:"general",num:126},
  {it:"molto",en:"very",he:"מאוד",level:"A1",cat:"adverbs",num:127},
  {it:"attraverso",en:"through",he:"דרך",level:"A1",cat:"grammar",num:128},
  {it:"solo",en:"just",he:"רק",level:"A1",cat:"adverbs",num:129},
  {it:"forma",en:"form",he:"טופס",level:"A1",cat:"general",num:130},
  {it:"frase",en:"sentence",he:"משפט",level:"A1",cat:"general",num:131},
  {it:"grande",en:"great",he:"גדול",level:"A1",cat:"general",num:132},
  {it:"pensare",en:"think",he:"לחשוב",level:"A1",cat:"verbs",num:133},
  {it:"dire",en:"say",he:"לומר",level:"A1",cat:"verbs",num:134},
  {it:"aiutare",en:"help",he:"עזרה",level:"A1",cat:"verbs",num:135},
  {it:"basso",en:"low",he:"נמוך",level:"A1",cat:"adjectives",num:136},
  {it:"linea",en:"line",he:"קו",level:"A1",cat:"general",num:137},
  {it:"differire",en:"differ",he:"להבדיל",level:"A1",cat:"verbs",num:138},
  {it:"turno",en:"turn",he:"לפנות",level:"A1",cat:"general",num:139},
  {it:"causa",en:"cause",he:"סיבה",level:"A1",cat:"general",num:140},
  {it:"molto",en:"much",he:"הרבה",level:"A1",cat:"adjectives",num:141},
  {it:"dire",en:"mean",he:"להתכוון",level:"A1",cat:"verbs",num:142},
  {it:"prima",en:"before",he:"לפני",level:"A1",cat:"grammar",num:143},
  {it:"spostare",en:"move",he:"לזוז",level:"A1",cat:"verbs",num:144},
  {it:"diritto",en:"right",he:"ימין/נכון",level:"A1",cat:"adjectives",num:145},
  {it:"ragazzo",en:"boy",he:"ילד",level:"A1",cat:"general",num:146},
  {it:"vecchio",en:"old",he:"ישן",level:"A1",cat:"adjectives",num:147},
  {it:"troppo",en:"too",he:"גם/מדי",level:"A1",cat:"adverbs",num:148},
  {it:"stesso",en:"same",he:"אותו",level:"A1",cat:"adjectives",num:149},
  {it:"lei",en:"she",he:"היא",level:"A1",cat:"pronouns",num:150},
  {it:"tutto",en:"all",he:"כל",level:"A1",cat:"adjectives",num:151},
  {it:"ci",en:"there",he:"שם",level:"A1",cat:"adverbs",num:152},
  {it:"quando",en:"when",he:"מתי",level:"A1",cat:"grammar",num:153},
  {it:"su",en:"up",he:"למעלה",level:"A1",cat:"adverbs",num:154},
  {it:"uso",en:"use",he:"להשתמש",level:"A1",cat:"general",num:155},
  {it:"il tuo",en:"your",he:"שלך",level:"A1",cat:"pronouns",num:156},
  {it:"modo",en:"way",he:"דרך",level:"A1",cat:"general",num:157},
  {it:"circa",en:"about",he:"בערך",level:"A1",cat:"grammar",num:158},
  {it:"molti",en:"many",he:"הרבה",level:"A1",cat:"adjectives",num:159},
  {it:"allora",en:"then",he:"אז",level:"A1",cat:"adverbs",num:160},
  {it:"loro",en:"them",he:"אותם",level:"A1",cat:"pronouns",num:161},
  {it:"scrivere",en:"write",he:"לכתוב",level:"A1",cat:"verbs",num:162},
  {it:"sarebbe",en:"would",he:"היה (תנאי)",level:"A1",cat:"general",num:163},
  {it:"come",en:"like",he:"איך/כמו",level:"A1",cat:"grammar",num:164},
  {it:"così",en:"so",he:"כך",level:"A1",cat:"adverbs",num:165},
  {it:"queste",en:"these",he:"אלה",level:"A1",cat:"general",num:166},
  {it:"lei",en:"her",he:"היא",level:"A1",cat:"pronouns",num:167},
  {it:"lungo",en:"long",he:"ארוך",level:"A1",cat:"adjectives",num:168},
  {it:"rendere",en:"make",he:"לעשות",level:"A1",cat:"verbs",num:169},
  {it:"cosa",en:"thing",he:"דבר",level:"A1",cat:"general",num:170},
  {it:"vedere",en:"see",he:"לראות",level:"A1",cat:"verbs",num:171},
  {it:"lui",en:"him",he:"אותו/הוא",level:"A1",cat:"pronouns",num:172},
  {it:"due",en:"two",he:"שניים",level:"A1",cat:"numbers",num:173},
  {it:"ha",en:"has",he:"יש לו/הוא",level:"A1",cat:"verbs",num:174},
  {it:"guardare",en:"look",he:"להסתכל",level:"A1",cat:"verbs",num:175},
  {it:"di più",en:"more",he:"יותר",level:"A1",cat:"adverbs",num:176},
  {it:"giorno",en:"day",he:"יום",level:"A1",cat:"time",num:177},
  {it:"potuto",en:"could",he:"יכול (עבר)",level:"A1",cat:"verbs",num:178},
  {it:"andare",en:"go",he:"ללכת",level:"A1",cat:"verbs",num:179},
  {it:"venire",en:"come",he:"לבוא",level:"A1",cat:"verbs",num:180},
  {it:"ha fatto",en:"did",he:"עשה",level:"A1",cat:"general",num:181},
  {it:"numero",en:"number",he:"מספר",level:"A1",cat:"general",num:182},
  {it:"suono",en:"sound",he:"צליל",level:"A1",cat:"general",num:183},
  {it:"no",en:"no",he:"לא",level:"A1",cat:"adverbs",num:184},
  {it:"più",en:"most",he:"הכי",level:"A1",cat:"adverbs",num:185},
  {it:"persone",en:"people",he:"אנשים",level:"A1",cat:"general",num:186},
  {it:"il mio",en:"my",he:"שלי",level:"A1",cat:"pronouns",num:187},
  {it:"oltre",en:"over",he:"מעל",level:"A1",cat:"grammar",num:188},
  {it:"sapere",en:"know",he:"לדעת",level:"A1",cat:"verbs",num:189},
  {it:"acqua",en:"water",he:"מים",level:"A1",cat:"food",num:190},
  {it:"di",en:"than",he:"מ",level:"A1",cat:"grammar",num:191},
  {it:"chiamata",en:"call",he:"להתקשר",level:"A1",cat:"verbs",num:192},
  {it:"primo",en:"first",he:"ראשון",level:"A1",cat:"numbers",num:193},
  {it:"che",en:"who",he:"מי",level:"A1",cat:"grammar",num:194},
  {it:"può",en:"may",he:"אולי",level:"A1",cat:"general",num:195},
  {it:"giù",en:"down",he:"למטה",level:"A1",cat:"adverbs",num:196},
  {it:"lato",en:"side",he:"צד",level:"A1",cat:"verbs",num:197},
  {it:"stato",en:"been",he:"היה (עבר)",level:"A1",cat:"verbs",num:198},
  {it:"ora",en:"now",he:"עכשיו",level:"A1",cat:"adverbs",num:199},
  {it:"trovare",en:"find",he:"למצוא",level:"A1",cat:"verbs",num:200},
  {it:"testa",en:"head",he:"ראש",level:"A2",cat:"body",num:201},
  {it:"stare in piedi",en:"stand",he:"לעמוד",level:"A2",cat:"general",num:202},
  {it:"proprio",en:"own",he:"שלו",level:"A2",cat:"general",num:203},
  {it:"pagina",en:"page",he:"עמוד",level:"A2",cat:"general",num:204},
  {it:"dovrebbe",en:"should",he:"צריך",level:"A2",cat:"general",num:205},
  {it:"paese",en:"country",he:"מדינה",level:"A2",cat:"places",num:206},
  {it:"fondare",en:"found",he:"לייסד",level:"A2",cat:"verbs",num:207},
  {it:"risposta",en:"answer",he:"תשובה",level:"A2",cat:"general",num:208},
  {it:"scuola",en:"school",he:"בית ספר",level:"A2",cat:"places",num:209},
  {it:"crescere",en:"grow",he:"לגדול",level:"A2",cat:"verbs",num:210},
  {it:"studio",en:"study",he:"סטודיו/לימוד",level:"A2",cat:"general",num:211},
  {it:"ancora",en:"still",he:"עדיין",level:"A2",cat:"adverbs",num:212},
  {it:"imparare",en:"learn",he:"ללמוד",level:"A2",cat:"body",num:213},
  {it:"impianto",en:"plant",he:"מתקן/צמח",level:"A2",cat:"general",num:214},
  {it:"copertura",en:"cover",he:"כיסוי",level:"A2",cat:"general",num:215},
  {it:"cibo",en:"food",he:"אוכל",level:"A2",cat:"food",num:216},
  {it:"sole",en:"sun",he:"שמש",level:"A2",cat:"general",num:217},
  {it:"quattro",en:"four",he:"ארבע",level:"A2",cat:"numbers",num:218},
  {it:"fra",en:"between",he:"בין",level:"A2",cat:"grammar",num:219},
  {it:"stato",en:"state",he:"מדינה",level:"A2",cat:"verbs",num:220},
  {it:"mantenere",en:"keep",he:"לשמור",level:"A2",cat:"verbs",num:221},
  {it:"occhio",en:"eye",he:"עין",level:"A2",cat:"body",num:222},
  {it:"mai",en:"never",he:"לעולם לא",level:"A2",cat:"adverbs",num:223},
  {it:"ultimo",en:"last",he:"אחרון",level:"A2",cat:"adjectives",num:224},
  {it:"lasciare",en:"let",he:"לתת",level:"A2",cat:"verbs",num:225},
  {it:"pensiero",en:"thought",he:"מחשבה",level:"A2",cat:"general",num:226},
  {it:"città",en:"city",he:"עיר",level:"A2",cat:"places",num:227},
  {it:"albero",en:"tree",he:"עץ",level:"A2",cat:"general",num:228},
  {it:"attraversare",en:"cross",he:"לחצות",level:"A2",cat:"verbs",num:229},
  {it:"fattoria",en:"farm",he:"חווה",level:"A2",cat:"body",num:230},
  {it:"difficile",en:"hard",he:"קשה",level:"A2",cat:"adjectives",num:231},
  {it:"inizio",en:"start",he:"התחלה",level:"A2",cat:"general",num:232},
  {it:"forza",en:"might",he:"אולי",level:"A2",cat:"general",num:233},
  {it:"storia",en:"story",he:"סיפור",level:"A2",cat:"general",num:234},
  {it:"sega",en:"saw",he:"מסור/ראה (עבר)",level:"A2",cat:"general",num:235},
  {it:"lontano",en:"far",he:"רחוק",level:"A2",cat:"adjectives",num:236},
  {it:"mare",en:"sea",he:"ים",level:"A2",cat:"verbs",num:237},
  {it:"disegnare",en:"draw",he:"לצייר",level:"A2",cat:"verbs",num:238},
  {it:"sinistra",en:"left",he:"שמאל",level:"A2",cat:"adjectives",num:239},
  {it:"tardi",en:"late",he:"מאוחר",level:"A2",cat:"general",num:240},
  {it:"run",en:"run",he:"לרוץ",level:"A2",cat:"general",num:241},
  {it:"non",en:"don’t",he:"לא",level:"A2",cat:"general",num:242},
  {it:"mentre",en:"while",he:"בזמן",level:"A2",cat:"grammar",num:243},
  {it:"stampa",en:"press",he:"עיתונות/דפוס",level:"A2",cat:"general",num:244},
  {it:"close",en:"close",he:"קרוב/לסגור",level:"A2",cat:"general",num:245},
  {it:"notte",en:"night",he:"לילה",level:"A2",cat:"time",num:246},
  {it:"reale",en:"real",he:"אמיתי",level:"A2",cat:"adjectives",num:247},
  {it:"vita",en:"life",he:"חיים",level:"A2",cat:"verbs",num:248},
  {it:"pochi",en:"few",he:"מעט",level:"A2",cat:"adjectives",num:249},
  {it:"nord",en:"north",he:"צפון",level:"A2",cat:"general",num:250},
  {it:"libro",en:"book",he:"ספר",level:"A2",cat:"general",num:251},
  {it:"portare",en:"carry",he:"לשאת",level:"A2",cat:"transport",num:252},
  {it:"ha preso",en:"took",he:"לקח",level:"A2",cat:"general",num:253},
  {it:"scienza",en:"science",he:"מדע",level:"A2",cat:"general",num:254},
  {it:"mangiare",en:"eat",he:"לאכול",level:"A2",cat:"verbs",num:255},
  {it:"camera",en:"room",he:"חדר",level:"A2",cat:"places",num:256},
  {it:"amico",en:"friend",he:"חבר",level:"A2",cat:"general",num:257},
  {it:"ha iniziato",en:"began",he:"התחיל",level:"A2",cat:"verbs",num:258},
  {it:"idea",en:"idea",he:"רעיון",level:"A2",cat:"general",num:259},
  {it:"pesce",en:"fish",he:"דג",level:"A2",cat:"food",num:260},
  {it:"montagna",en:"mountain",he:"הר",level:"A2",cat:"places",num:261},
  {it:"stop",en:"stop",he:"לעצור",level:"A2",cat:"general",num:262},
  {it:"una volta",en:"once",he:"פעם אחת",level:"A2",cat:"general",num:263},
  {it:"base",en:"base",he:"בסיס",level:"A2",cat:"general",num:264},
  {it:"sentire",en:"hear",he:"לשמוע",level:"A2",cat:"body",num:265},
  {it:"cavallo",en:"horse",he:"סוס",level:"A2",cat:"animals",num:266},
  {it:"taglio",en:"cut",he:"לחתוך",level:"A2",cat:"general",num:267},
  {it:"sicuro",en:"sure",he:"בטוח",level:"A2",cat:"adjectives",num:268},
  {it:"orologio",en:"watch",he:"שעון",level:"A2",cat:"general",num:269},
  {it:"colore",en:"color",he:"צבע",level:"A2",cat:"general",num:270},
  {it:"volto",en:"face",he:"פנים",level:"A2",cat:"body",num:271},
  {it:"legno",en:"wood",he:"עץ",level:"A2",cat:"general",num:272},
  {it:"principale",en:"main",he:"ראשי",level:"A2",cat:"adjectives",num:273},
  {it:"aperto",en:"open",he:"פתוח",level:"A2",cat:"adjectives",num:274},
  {it:"sembrare",en:"seem",he:"להיראות",level:"A2",cat:"verbs",num:275},
  {it:"insieme",en:"together",he:"יחד",level:"A2",cat:"adverbs",num:276},
  {it:"prossimo",en:"next",he:"הבא",level:"A2",cat:"adjectives",num:277},
  {it:"bianco",en:"white",he:"לבן",level:"A2",cat:"adjectives",num:278},
  {it:"bambini",en:"children",he:"ילדים",level:"A2",cat:"family",num:279},
  {it:"inizio",en:"begin",he:"להתחיל",level:"A2",cat:"general",num:280},
  {it:"ottenuto",en:"got",he:"השיג (עבר)",level:"A2",cat:"verbs",num:281},
  {it:"camminare",en:"walk",he:"ללכת",level:"A2",cat:"verbs",num:282},
  {it:"esempio",en:"example",he:"דוגמה",level:"A2",cat:"general",num:283},
  {it:"alleviare",en:"ease",he:"להקל",level:"A2",cat:"verbs",num:284},
  {it:"carta",en:"paper",he:"נייר",level:"A2",cat:"general",num:285},
  {it:"gruppo",en:"group",he:"קבוצה",level:"A2",cat:"general",num:286},
  {it:"sempre",en:"always",he:"תמיד",level:"A2",cat:"adverbs",num:287},
  {it:"musica",en:"music",he:"מוזיקה",level:"A2",cat:"general",num:288},
  {it:"quelli",en:"those",he:"אלה",level:"A2",cat:"general",num:289},
  {it:"entrambi",en:"both",he:"שניהם",level:"A2",cat:"general",num:290},
  {it:"marchio",en:"mark",he:"מותג/סימן",level:"A2",cat:"general",num:291},
  {it:"spesso",en:"often",he:"לעתים קרובות",level:"A2",cat:"adverbs",num:292},
  {it:"lettera",en:"letter",he:"מכתב",level:"A2",cat:"general",num:293},
  {it:"fino a quando",en:"until",he:"עד",level:"A2",cat:"grammar",num:294},
  {it:"miglio",en:"mile",he:"מייל",level:"A2",cat:"general",num:295},
  {it:"fiume",en:"river",he:"נהר",level:"A2",cat:"general",num:296},
  {it:"auto",en:"car",he:"מכונית",level:"A2",cat:"transport",num:297},
  {it:"piedi",en:"feet",he:"רגליים",level:"A2",cat:"general",num:298},
  {it:"cura",en:"care",he:"טיפול/דאגה",level:"A2",cat:"transport",num:299},
  {it:"secondo",en:"second",he:"שנייה",level:"A2",cat:"numbers",num:300},
  {it:"abbastanza",en:"enough",he:"מספיק",level:"A2",cat:"adjectives",num:301},
  {it:"pianura",en:"plain",he:"מישור",level:"A2",cat:"general",num:302},
  {it:"ragazza",en:"girl",he:"ילדה",level:"A2",cat:"general",num:303},
  {it:"solito",en:"usual",he:"רגיל",level:"A2",cat:"adjectives",num:304},
  {it:"giovane",en:"young",he:"צעיר",level:"A2",cat:"pronouns",num:305},
  {it:"pronto",en:"ready",he:"מוכן",level:"A2",cat:"adjectives",num:306},
  {it:"sopra",en:"above",he:"מעל",level:"A2",cat:"grammar",num:307},
  {it:"mai",en:"ever",he:"לעולם לא",level:"A2",cat:"general",num:308},
  {it:"rosso",en:"red",he:"אדום",level:"A2",cat:"adjectives",num:309},
  {it:"elenco",en:"list",he:"רשימה",level:"A2",cat:"general",num:310},
  {it:"anche se",en:"though",he:"למרות ש",level:"A2",cat:"general",num:311},
  {it:"sentire",en:"feel",he:"להרגיש",level:"A2",cat:"verbs",num:312},
  {it:"Discussioni",en:"talk",he:"לדבר/שיחה",level:"A2",cat:"general",num:313},
  {it:"uccello",en:"bird",he:"ציפור",level:"A2",cat:"animals",num:314},
  {it:"presto",en:"soon",he:"בקרוב/מוקדם",level:"A2",cat:"adverbs",num:315},
  {it:"corpo",en:"body",he:"גוף",level:"A2",cat:"body",num:316},
  {it:"cane",en:"dog",he:"כלב",level:"A2",cat:"animals",num:317},
  {it:"famiglia",en:"family",he:"משפחה",level:"A2",cat:"family",num:318},
  {it:"diretto",en:"direct",he:"ישיר",level:"A2",cat:"general",num:319},
  {it:"posa",en:"pose",he:"תנוחה",level:"A2",cat:"general",num:320},
  {it:"lasciare",en:"leave",he:"לעזוב",level:"A2",cat:"verbs",num:321},
  {it:"canzone",en:"song",he:"שיר",level:"A2",cat:"family",num:322},
  {it:"misurare",en:"measure",he:"למדוד",level:"A2",cat:"verbs",num:323},
  {it:"porta",en:"door",he:"דלת",level:"A2",cat:"places",num:324},
  {it:"prodotto",en:"product",he:"מוצר",level:"A2",cat:"general",num:325},
  {it:"nero",en:"black",he:"שחור",level:"A2",cat:"adjectives",num:326},
  {it:"breve",en:"short",he:"קצר",level:"A2",cat:"adjectives",num:327},
  {it:"numerale",en:"numeral",he:"מספרי",level:"A2",cat:"general",num:328},
  {it:"classe",en:"class",he:"כיתה",level:"A2",cat:"general",num:329},
  {it:"vento",en:"wind",he:"רוח",level:"A2",cat:"general",num:330},
  {it:"domanda",en:"question",he:"שאלה",level:"A2",cat:"general",num:331},
  {it:"accadere",en:"happen",he:"לקרות",level:"A2",cat:"verbs",num:332},
  {it:"integrale",en:"complete",he:"שלם",level:"A2",cat:"adjectives",num:333},
  {it:"nave",en:"ship",he:"ספינה",level:"A2",cat:"transport",num:334},
  {it:"area",en:"area",he:"אזור",level:"A2",cat:"general",num:335},
  {it:"metà",en:"half",he:"חצי",level:"A2",cat:"adjectives",num:336},
  {it:"rock",en:"rock",he:"סלע",level:"A2",cat:"general",num:337},
  {it:"ordine",en:"order",he:"סדר",level:"A2",cat:"general",num:338},
  {it:"fuoco",en:"fire",he:"אש",level:"A2",cat:"general",num:339},
  {it:"sud",en:"south",he:"דרום",level:"A2",cat:"general",num:340},
  {it:"problema",en:"problem",he:"בעיה",level:"A2",cat:"general",num:341},
  {it:"pezzo",en:"piece",he:"חתיכה",level:"A2",cat:"general",num:342},
  {it:"ha detto",en:"told",he:"אמר",level:"A2",cat:"general",num:343},
  {it:"sapeva",en:"knew",he:"ידע (עבר)",level:"A2",cat:"general",num:344},
  {it:"passare",en:"pass",he:"לעבור",level:"A2",cat:"verbs",num:345},
  {it:"da",en:"since",he:"מאז",level:"A2",cat:"grammar",num:346},
  {it:"top",en:"top",he:"למעלה",level:"A2",cat:"general",num:347},
  {it:"tutto",en:"whole",he:"שלם",level:"A2",cat:"adjectives",num:348},
  {it:"re",en:"king",he:"מלך",level:"A2",cat:"general",num:349},
  {it:"strada",en:"street",he:"רחוב",level:"A2",cat:"places",num:350},
  {it:"pollice",en:"inch",he:"אינץ\'/אגודל",level:"A2",cat:"general",num:351},
  {it:"moltiplicare",en:"multiply",he:"להכפיל",level:"A2",cat:"verbs",num:352},
  {it:"niente",en:"nothing",he:"כלום",level:"A2",cat:"general",num:353},
  {it:"corso",en:"course",he:"קורס/מסלול",level:"A2",cat:"general",num:354},
  {it:"soggiornare",en:"stay",he:"לשהות",level:"A2",cat:"verbs",num:355},
  {it:"ruota",en:"wheel",he:"גלגל",level:"A2",cat:"general",num:356},
  {it:"completo",en:"full",he:"מלא",level:"A2",cat:"adjectives",num:357},
  {it:"vigore",en:"force",he:"חוסן",level:"A2",cat:"general",num:358},
  {it:"blu",en:"blue",he:"כחול",level:"A2",cat:"adjectives",num:359},
  {it:"oggetto",en:"object",he:"חפץ",level:"A2",cat:"general",num:360},
  {it:"decidere",en:"decide",he:"להחליט",level:"A2",cat:"verbs",num:361},
  {it:"superficie",en:"surface",he:"שטח",level:"A2",cat:"body",num:362},
  {it:"profondità",en:"deep",he:"עמוק",level:"A2",cat:"adjectives",num:363},
  {it:"luna",en:"moon",he:"ירח",level:"A2",cat:"general",num:364},
  {it:"isola",en:"island",he:"אי",level:"A2",cat:"places",num:365},
  {it:"piede",en:"foot",he:"רגל",level:"A2",cat:"body",num:366},
  {it:"sistema",en:"system",he:"מערכת",level:"A2",cat:"general",num:367},
  {it:"occupato",en:"busy",he:"עסוק",level:"A2",cat:"transport",num:368},
  {it:"test",en:"test",he:"מבחן/בדיקה",level:"A2",cat:"general",num:369},
  {it:"record",en:"record",he:"רשומה",level:"A2",cat:"general",num:370},
  {it:"barca",en:"boat",he:"סירה",level:"A2",cat:"transport",num:371},
  {it:"comune",en:"common",he:"נפוץ",level:"A2",cat:"adjectives",num:372},
  {it:"oro",en:"gold",he:"זהב",level:"A2",cat:"general",num:373},
  {it:"possibile",en:"possible",he:"אפשרי",level:"A2",cat:"adjectives",num:374},
  {it:"piano",en:"plane",he:"תוכנית/מישור/פסנתר",level:"A2",cat:"general",num:375},
  {it:"vece",en:"stead",he:"במקום",level:"A2",cat:"food",num:376},
  {it:"asciutto",en:"dry",he:"יבש",level:"A2",cat:"adjectives",num:377},
  {it:"meraviglia",en:"wonder",he:"פלא",level:"A2",cat:"general",num:378},
  {it:"ridere",en:"laugh",he:"לצחוק",level:"A2",cat:"verbs",num:379},
  {it:"migliaia",en:"thousand",he:"אלף",level:"A2",cat:"numbers",num:380},
  {it:"fa",en:"ago",he:"לפני",level:"A2",cat:"general",num:381},
  {it:"corse",en:"ran",he:"רץ",level:"A2",cat:"general",num:382},
  {it:"controllare",en:"check",he:"לבדוק",level:"A2",cat:"verbs",num:383},
  {it:"gioco",en:"game",he:"משחק",level:"A2",cat:"general",num:384},
  {it:"forma",en:"shape",he:"צורה",level:"A2",cat:"general",num:385},
  {it:"uguagliare",en:"equate",he:"להשוות",level:"A2",cat:"verbs",num:386},
  {it:"caldo",en:"hot",he:"חם",level:"A2",cat:"adjectives",num:387},
  {it:"perdere",en:"miss",he:"לאבד/להפסיד",level:"A2",cat:"verbs",num:388},
  {it:"portato",en:"brought",he:"הובא",level:"A2",cat:"verbs",num:389},
  {it:"calore",en:"heat",he:"חום (טמפ\')",level:"A2",cat:"general",num:390},
  {it:"neve",en:"snow",he:"שלג",level:"A2",cat:"general",num:391},
  {it:"pneumatico",en:"tire",he:"צמיג",level:"A2",cat:"general",num:392},
  {it:"portare",en:"bring",he:"להביא",level:"A2",cat:"verbs",num:393},
  {it:"sì",en:"yes",he:"כן",level:"A2",cat:"adverbs",num:394},
  {it:"lontano",en:"distant",he:"רחוק",level:"A2",cat:"general",num:395},
  {it:"riempire",en:"fill",he:"למלא",level:"A2",cat:"verbs",num:396},
  {it:"est",en:"east",he:"מזרח",level:"A2",cat:"general",num:397},
  {it:"dipingere",en:"paint",he:"לצייר",level:"A2",cat:"verbs",num:398},
  {it:"lingua",en:"language",he:"שפה",level:"A2",cat:"general",num:399},
  {it:"tra",en:"among",he:"בין",level:"A2",cat:"grammar",num:400},
  {it:"unità",en:"unit",he:"יחידה",level:"B1",cat:"general",num:401},
  {it:"potenza",en:"power",he:"כוח",level:"B1",cat:"general",num:402},
  {it:"città",en:"town",he:"עיר",level:"B1",cat:"places",num:403},
  {it:"fine",en:"fine",he:"קנס/טוב",level:"B1",cat:"general",num:404},
  {it:"certo",en:"certain",he:"מסוים",level:"B1",cat:"adjectives",num:405},
  {it:"volare",en:"fly",he:"לעוף",level:"B1",cat:"verbs",num:406},
  {it:"cadere",en:"fall",he:"ליפול",level:"B1",cat:"verbs",num:407},
  {it:"portare",en:"lead",he:"לשאת/להוביל",level:"B1",cat:"verbs",num:408},
  {it:"grido",en:"cry",he:"לבכות",level:"B1",cat:"general",num:409},
  {it:"scuro",en:"dark",he:"חושך",level:"B1",cat:"adjectives",num:410},
  {it:"macchina",en:"machine",he:"מכונה",level:"B1",cat:"general",num:411},
  {it:"nota",en:"note",he:"הערה/תו",level:"B1",cat:"general",num:412},
  {it:"aspettare",en:"wait",he:"לחכות",level:"B1",cat:"verbs",num:413},
  {it:"piano",en:"plan",he:"תכנית",level:"B1",cat:"general",num:414},
  {it:"figura",en:"figure",he:"דמות/צורה",level:"B1",cat:"general",num:415},
  {it:"stella",en:"star",he:"כוכב",level:"B1",cat:"general",num:416},
  {it:"scatola",en:"box",he:"קופסה",level:"B1",cat:"general",num:417},
  {it:"sostantivo",en:"noun",he:"שם עצם",level:"B1",cat:"general",num:418},
  {it:"campo",en:"field",he:"שדה",level:"B1",cat:"general",num:419},
  {it:"resto",en:"rest",he:"שארית",level:"B1",cat:"general",num:420},
  {it:"corretto",en:"correct",he:"נכון",level:"B1",cat:"adjectives",num:421},
  {it:"in grado di",en:"able",he:"מסוגל",level:"B1",cat:"general",num:422},
  {it:"libbra",en:"pound",he:"פאונד",level:"B1",cat:"general",num:423},
  {it:"done",en:"done",he:"בוצע",level:"B1",cat:"general",num:424},
  {it:"bellezza",en:"beauty",he:"יופי",level:"B1",cat:"general",num:425},
  {it:"unità",en:"drive",he:"לנהוג",level:"B1",cat:"general",num:426},
  {it:"sorgeva",en:"stood",he:"קם",level:"B1",cat:"general",num:427},
  {it:"contenere",en:"contain",he:"להכיל",level:"B1",cat:"verbs",num:428},
  {it:"frontale",en:"front",he:"חזית",level:"B1",cat:"general",num:429},
  {it:"insegnare",en:"teach",he:"ללמד",level:"B1",cat:"food",num:430},
  {it:"settimana",en:"week",he:"שבוע",level:"B1",cat:"time",num:431},
  {it:"finale",en:"final",he:"סופי",level:"B1",cat:"adjectives",num:432},
  {it:"ha dato",en:"gave",he:"נתן",level:"B1",cat:"verbs",num:433},
  {it:"verde",en:"green",he:"ירוק",level:"B1",cat:"adjectives",num:434},
  {it:"oh",en:"oh",he:"הו",level:"B1",cat:"general",num:435},
  {it:"veloce",en:"quick",he:"מהיר",level:"B1",cat:"general",num:436},
  {it:"sviluppare",en:"develop",he:"לפתח",level:"B1",cat:"verbs",num:437},
  {it:"oceano",en:"ocean",he:"אוקיינוס",level:"B1",cat:"general",num:438},
  {it:"caldo",en:"warm",he:"חם",level:"B1",cat:"body",num:439},
  {it:"gratuito",en:"free",he:"חופשי",level:"B1",cat:"adjectives",num:440},
  {it:"minuto",en:"minute",he:"דקה",level:"B1",cat:"time",num:441},
  {it:"forte",en:"strong",he:"חזק",level:"B1",cat:"adjectives",num:442},
  {it:"speciale",en:"special",he:"מיוחד",level:"B1",cat:"adjectives",num:443},
  {it:"mente",en:"mind",he:"מוח",level:"B1",cat:"general",num:444},
  {it:"dietro",en:"behind",he:"מאחורי",level:"B1",cat:"grammar",num:445},
  {it:"chiaro",en:"clear",he:"ברור",level:"B1",cat:"body",num:446},
  {it:"coda",en:"tail",he:"זנב/תור",level:"B1",cat:"general",num:447},
  {it:"produrre",en:"produce",he:"לייצר",level:"B1",cat:"general",num:448},
  {it:"fatto",en:"fact",he:"עובדה",level:"B1",cat:"general",num:449},
  {it:"spazio",en:"space",he:"מרחב",level:"B1",cat:"general",num:450},
  {it:"sentito",en:"heard",he:"שמע",level:"B1",cat:"body",num:451},
  {it:"migliore",en:"best",he:"הטוב ביותר",level:"B1",cat:"general",num:452},
  {it:"ora",en:"hour",he:"שעה",level:"B1",cat:"time",num:453},
  {it:"meglio",en:"better",he:"יותר טוב",level:"B1",cat:"general",num:454},
  {it:"vero",en:"true",he:"אמיתי",level:"B1",cat:"adjectives",num:455},
  {it:"durante",en:"during",he:"במהלך",level:"B1",cat:"grammar",num:456},
  {it:"cento",en:"hundred",he:"מאה",level:"B1",cat:"numbers",num:457},
  {it:"cinque",en:"five",he:"חמש",level:"B1",cat:"numbers",num:458},
  {it:"ricordare",en:"remember",he:"לזכור",level:"B1",cat:"verbs",num:459},
  {it:"passo",en:"step",he:"צעד",level:"B1",cat:"general",num:460},
  {it:"presto",en:"early",he:"בקרוב/מוקדם",level:"B1",cat:"body",num:461},
  {it:"tenere",en:"hold",he:"להחזיק",level:"B1",cat:"verbs",num:462},
  {it:"ovest",en:"west",he:"מערב",level:"B1",cat:"general",num:463},
  {it:"terra",en:"ground",he:"קרקע",level:"B1",cat:"general",num:464},
  {it:"interesse",en:"interest",he:"עניין",level:"B1",cat:"general",num:465},
  {it:"raggiungere",en:"reach",he:"להשיג",level:"B1",cat:"verbs",num:466},
  {it:"veloce",en:"fast",he:"מהיר",level:"B1",cat:"adjectives",num:467},
  {it:"verbo",en:"verb",he:"פועל (דקדוק)",level:"B1",cat:"general",num:468},
  {it:"cantare",en:"sing",he:"לשיר",level:"B1",cat:"verbs",num:469},
  {it:"ascoltare",en:"listen",he:"להקשיב",level:"B1",cat:"verbs",num:470},
  {it:"sei",en:"six",he:"שש",level:"B1",cat:"numbers",num:471},
  {it:"tavolo",en:"table",he:"שולחן",level:"B1",cat:"general",num:472},
  {it:"viaggi",en:"travel",he:"נסיעות",level:"B1",cat:"transport",num:473},
  {it:"meno",en:"less",he:"פחות",level:"B1",cat:"adverbs",num:474},
  {it:"mattina",en:"morning",he:"בוקר",level:"B1",cat:"time",num:475},
  {it:"dieci",en:"ten",he:"עשר",level:"B1",cat:"numbers",num:476},
  {it:"semplice",en:"simple",he:"פשוט",level:"B1",cat:"adjectives",num:477},
  {it:"alcuni",en:"several",he:"כמה",level:"B1",cat:"general",num:478},
  {it:"vocale",en:"vowel",he:"תנועה (דקדוק)",level:"B1",cat:"general",num:479},
  {it:"verso",en:"toward",he:"לעבר",level:"B1",cat:"grammar",num:480},
  {it:"guerra",en:"war",he:"מלחמה",level:"B1",cat:"general",num:481},
  {it:"porre",en:"lay",he:"להניח",level:"B1",cat:"general",num:482},
  {it:"contro",en:"against",he:"נגד",level:"B1",cat:"grammar",num:483},
  {it:"modello",en:"pattern",he:"דגם",level:"B1",cat:"general",num:484},
  {it:"lento",en:"slow",he:"איטי",level:"B1",cat:"adjectives",num:485},
  {it:"centro",en:"center",he:"מרכז",level:"B1",cat:"general",num:486},
  {it:"amore",en:"love",he:"אהבה",level:"B1",cat:"general",num:487},
  {it:"persona",en:"person",he:"אדם",level:"B1",cat:"family",num:488},
  {it:"soldi",en:"money",he:"כסף",level:"B1",cat:"general",num:489},
  {it:"servire",en:"serve",he:"לשרת",level:"B1",cat:"verbs",num:490},
  {it:"apparire",en:"appear",he:"להופיע",level:"B1",cat:"body",num:491},
  {it:"strada",en:"road",he:"כביש",level:"B1",cat:"places",num:492},
  {it:"mappa",en:"map",he:"מפה",level:"B1",cat:"general",num:493},
  {it:"pioggia",en:"rain",he:"גשם",level:"B1",cat:"general",num:494},
  {it:"regola",en:"rule",he:"כלל",level:"B1",cat:"general",num:495},
  {it:"governare",en:"govern",he:"לשלוט",level:"B1",cat:"verbs",num:496},
  {it:"tirare",en:"pull",he:"למשוך",level:"B1",cat:"verbs",num:497},
  {it:"freddo",en:"cold",he:"קר",level:"B1",cat:"adjectives",num:498},
  {it:"avviso",en:"notice",he:"הודעה",level:"B1",cat:"general",num:499},
  {it:"voce",en:"voice",he:"קול",level:"B1",cat:"general",num:500},
  {it:"energia",en:"energy",he:"אנרגיה",level:"B1",cat:"general",num:501},
  {it:"caccia",en:"hunt",he:"ציד",level:"B1",cat:"general",num:502},
  {it:"probabile",en:"probable",he:"סביר",level:"B1",cat:"general",num:503},
  {it:"letto",en:"bed",he:"מיטה",level:"B1",cat:"places",num:504},
  {it:"fratello",en:"brother",he:"אח",level:"B1",cat:"family",num:505},
  {it:"uovo",en:"egg",he:"ביצה",level:"B1",cat:"food",num:506},
  {it:"giro",en:"ride",he:"סיבוב",level:"B1",cat:"general",num:507},
  {it:"cella",en:"cell",he:"תא",level:"B1",cat:"general",num:508},
  {it:"credere",en:"believe",he:"להאמין",level:"B1",cat:"verbs",num:509},
  {it:"forse",en:"perhaps",he:"אולי",level:"B1",cat:"adverbs",num:510},
  {it:"scegliere",en:"pick",he:"לבחור",level:"B1",cat:"verbs",num:511},
  {it:"improvviso",en:"sudden",he:"פתאומי",level:"B1",cat:"general",num:512},
  {it:"contare",en:"count",he:"לספור",level:"B1",cat:"verbs",num:513},
  {it:"piazza",en:"square",he:"כיכר",level:"B1",cat:"places",num:514},
  {it:"motivo",en:"reason",he:"סיבה",level:"B1",cat:"family",num:515},
  {it:"lunghezza",en:"length",he:"אורך",level:"B1",cat:"general",num:516},
  {it:"rappresentare",en:"represent",he:"לייצג",level:"B1",cat:"verbs",num:517},
  {it:"arte",en:"art",he:"אמנות",level:"B1",cat:"general",num:518},
  {it:"soggetto",en:"subject",he:"נושא",level:"B1",cat:"general",num:519},
  {it:"regione",en:"region",he:"אזור",level:"B1",cat:"places",num:520},
  {it:"dimensione",en:"size",he:"גודל",level:"B1",cat:"general",num:521},
  {it:"variare",en:"vary",he:"להשתנות",level:"B1",cat:"verbs",num:522},
  {it:"risolvere",en:"settle",he:"לפתור",level:"B1",cat:"verbs",num:523},
  {it:"parlare",en:"speak",he:"לדבר",level:"B1",cat:"verbs",num:524},
  {it:"peso",en:"weight",he:"משקל",level:"B1",cat:"general",num:525},
  {it:"generale",en:"general",he:"כללי",level:"B1",cat:"adjectives",num:526},
  {it:"ghiaccio",en:"ice",he:"קרח",level:"B1",cat:"general",num:527},
  {it:"materia",en:"matter",he:"חומר/מקצוע",level:"B1",cat:"general",num:528},
  {it:"cerchio",en:"circle",he:"עיגול",level:"B1",cat:"general",num:529},
  {it:"coppia",en:"pair",he:"זוג",level:"B1",cat:"general",num:530},
  {it:"includere",en:"include",he:"לכלול",level:"B1",cat:"verbs",num:531},
  {it:"divide",en:"divide",he:"לחלק",level:"B1",cat:"general",num:532},
  {it:"sillaba",en:"syllable",he:"הברה",level:"B1",cat:"general",num:533},
  {it:"feltro",en:"felt",he:"לבד/הרגיש",level:"B1",cat:"general",num:534},
  {it:"grande",en:"grand",he:"גדול",level:"B1",cat:"general",num:535},
  {it:"palla",en:"ball",he:"כדור",level:"B1",cat:"general",num:536},
  {it:"ancora",en:"yet",he:"עדיין",level:"B1",cat:"adverbs",num:537},
  {it:"onda",en:"wave",he:"גל",level:"B1",cat:"general",num:538},
  {it:"cadere",en:"drop",he:"טיפה",level:"B1",cat:"verbs",num:539},
  {it:"cuore",en:"heart",he:"לב",level:"B1",cat:"body",num:540},
  {it:"am",en:"am",he:"אני (am)",level:"B1",cat:"general",num:541},
  {it:"presente",en:"present",he:"מתנה/הווה/להציג",level:"B1",cat:"general",num:542},
  {it:"pesante",en:"heavy",he:"כבד",level:"B1",cat:"adjectives",num:543},
  {it:"danza",en:"dance",he:"לרקוד",level:"B1",cat:"general",num:544},
  {it:"motore",en:"engine",he:"[engine]",level:"B1",cat:"general",num:545},
  {it:"posizione",en:"position",he:"[position]",level:"B1",cat:"general",num:546},
  {it:"braccio",en:"arm",he:"יד",level:"B1",cat:"body",num:547},
  {it:"ampio",en:"wide",he:"רחב",level:"B1",cat:"adjectives",num:548},
  {it:"vela",en:"sail",he:"[sail]",level:"B1",cat:"general",num:549},
  {it:"materiale",en:"material",he:"חומר",level:"B1",cat:"general",num:550},
  {it:"frazione",en:"fraction",he:"[fraction]",level:"B1",cat:"general",num:551},
  {it:"foresta",en:"forest",he:"יער",level:"B1",cat:"places",num:552},
  {it:"sedersi",en:"sit",he:"לשבת",level:"B1",cat:"verbs",num:553},
  {it:"gara",en:"race",he:"[race]",level:"B1",cat:"general",num:554},
  {it:"finestra",en:"window",he:"חלון",level:"B1",cat:"places",num:555},
  {it:"negozio",en:"store",he:"חנות",level:"B1",cat:"general",num:556},
  {it:"estate",en:"summer",he:"קיץ",level:"B1",cat:"time",num:557},
  {it:"treno",en:"train",he:"רכבת",level:"B1",cat:"transport",num:558},
  {it:"sonno",en:"sleep",he:"לישון",level:"B1",cat:"general",num:559},
  {it:"dimostrare",en:"prove",he:"[prove]",level:"B1",cat:"verbs",num:560},
  {it:"solitario",en:"lone",he:"[lone]",level:"B1",cat:"general",num:561},
  {it:"gamba",en:"leg",he:"רגל",level:"B1",cat:"body",num:562},
  {it:"esercizio",en:"exercise",he:"[exercise]",level:"B1",cat:"general",num:563},
  {it:"muro",en:"wall",he:"[wall]",level:"B1",cat:"general",num:564},
  {it:"prendere",en:"catch",he:"לקחת",level:"B1",cat:"verbs",num:565},
  {it:"monte",en:"mount",he:"[mount]",level:"B1",cat:"general",num:566},
  {it:"desiderio",en:"wish",he:"[wish]",level:"B1",cat:"general",num:567},
  {it:"cielo",en:"sky",he:"שמיים",level:"B1",cat:"general",num:568},
  {it:"pensione",en:"board",he:"[board]",level:"B1",cat:"general",num:569},
  {it:"gioia",en:"joy",he:"[joy]",level:"B1",cat:"general",num:570},
  {it:"inverno",en:"winter",he:"חורף",level:"B1",cat:"time",num:571},
  {it:"sat",en:"sat",he:"[sat]",level:"B1",cat:"general",num:572},
  {it:"scritto",en:"written",he:"[written]",level:"B1",cat:"general",num:573},
  {it:"selvaggio",en:"wild",he:"[wild]",level:"B1",cat:"general",num:574},
  {it:"strumento",en:"instrument",he:"[instrument]",level:"B1",cat:"general",num:575},
  {it:"tenere",en:"kept",he:"להחזיק",level:"B1",cat:"verbs",num:576},
  {it:"vetro",en:"glass",he:"זכוכית",level:"B1",cat:"general",num:577},
  {it:"erba",en:"grass",he:"דשא/עשב",level:"B1",cat:"general",num:578},
  {it:"mucca",en:"cow",he:"[cow]",level:"B1",cat:"animals",num:579},
  {it:"lavoro",en:"job",he:"עבודה",level:"B1",cat:"general",num:580},
  {it:"bordo",en:"edge",he:"קצה",level:"B1",cat:"general",num:581},
  {it:"segno",en:"sign",he:"סימן",level:"B1",cat:"general",num:582},
  {it:"visita",en:"visit",he:"[visit]",level:"B1",cat:"verbs",num:583},
  {it:"passato",en:"past",he:"[past]",level:"B1",cat:"verbs",num:584},
  {it:"morbido",en:"soft",he:"רך",level:"B1",cat:"adjectives",num:585},
  {it:"divertimento",en:"fun",he:"[fun]",level:"B1",cat:"general",num:586},
  {it:"luminoso",en:"bright",he:"[bright]",level:"B1",cat:"general",num:587},
  {it:"gas",en:"gas",he:"[gas]",level:"B1",cat:"general",num:588},
  {it:"tempo",en:"weather",he:"זמן",level:"B1",cat:"general",num:589},
  {it:"mese",en:"month",he:"חודש",level:"B1",cat:"time",num:590},
  {it:"milione",en:"million",he:"מיליון",level:"B1",cat:"numbers",num:591},
  {it:"sopportare",en:"bear",he:"[bear]",level:"B1",cat:"body",num:592},
  {it:"finitura",en:"finish",he:"לסיים",level:"B1",cat:"general",num:593},
  {it:"felice",en:"happy",he:"שמח",level:"B1",cat:"adjectives",num:594},
  {it:"speranza",en:"hope",he:"תקווה",level:"B1",cat:"general",num:595},
  {it:"fiore",en:"flower",he:"פרח",level:"B1",cat:"general",num:596},
  {it:"vestire",en:"clothe",he:"ללבוש",level:"B1",cat:"verbs",num:597},
  {it:"strano",en:"strange",he:"מוזר",level:"B1",cat:"adjectives",num:598},
  {it:"gone",en:"gone",he:"[gone]",level:"B1",cat:"general",num:599},
  {it:"commercio",en:"trade",he:"[trade]",level:"B1",cat:"general",num:600},
  {it:"melodia",en:"melody",he:"[melody]",level:"B2",cat:"general",num:601},
  {it:"viaggio",en:"trip",he:"טיול",level:"B2",cat:"transport",num:602},
  {it:"ufficio",en:"office",he:"משרד",level:"B2",cat:"places",num:603},
  {it:"ricevere",en:"receive",he:"לקבל",level:"B2",cat:"verbs",num:604},
  {it:"fila",en:"row",he:"[row]",level:"B2",cat:"general",num:605},
  {it:"bocca",en:"mouth",he:"פה",level:"B2",cat:"body",num:606},
  {it:"esatto",en:"exact",he:"[exact]",level:"B2",cat:"general",num:607},
  {it:"simbolo",en:"symbol",he:"[symbol]",level:"B2",cat:"general",num:608},
  {it:"morire",en:"die",he:"למות",level:"B2",cat:"verbs",num:609},
  {it:"meno",en:"least",he:"הכי פחות",level:"B2",cat:"adverbs",num:610},
  {it:"difficoltà",en:"trouble",he:"[trouble]",level:"B2",cat:"general",num:611},
  {it:"shout",en:"shout",he:"[shout]",level:"B2",cat:"general",num:612},
  {it:"tranne",en:"except",he:"[except]",level:"B2",cat:"general",num:613},
  {it:"ha scritto",en:"wrote",he:"[wrote]",level:"B2",cat:"general",num:614},
  {it:"seme",en:"seed",he:"[seed]",level:"B2",cat:"general",num:615},
  {it:"tono",en:"tone",he:"[tone]",level:"B2",cat:"general",num:616},
  {it:"aderire",en:"join",he:"להצטרף",level:"B2",cat:"verbs",num:617},
  {it:"suggerire",en:"suggest",he:"[suggest]",level:"B2",cat:"verbs",num:618},
  {it:"pulito",en:"clean",he:"נקי",level:"B2",cat:"verbs",num:619},
  {it:"pausa",en:"break",he:"[break]",level:"B2",cat:"general",num:620},
  {it:"signora",en:"lady",he:"[lady]",level:"B2",cat:"general",num:621},
  {it:"cantiere",en:"yard",he:"[yard]",level:"B2",cat:"verbs",num:622},
  {it:"salire",en:"rise",he:"לעלות",level:"B2",cat:"verbs",num:623},
  {it:"male",en:"bad",he:"רע",level:"B2",cat:"adjectives",num:624},
  {it:"colpo",en:"blow",he:"[blow]",level:"B2",cat:"general",num:625},
  {it:"olio",en:"oil",he:"שמן",level:"B2",cat:"food",num:626},
  {it:"sangue",en:"blood",he:"דם",level:"B2",cat:"body",num:627},
  {it:"toccare",en:"touch",he:"[touch]",level:"B2",cat:"verbs",num:628},
  {it:"è cresciuto",en:"grew",he:"[grew]",level:"B2",cat:"verbs",num:629},
  {it:"cent",en:"cent",he:"[cent]",level:"B2",cat:"general",num:630},
  {it:"mescolare",en:"mix",he:"[mix]",level:"B2",cat:"verbs",num:631},
  {it:"team",en:"team",he:"קבוצה",level:"B2",cat:"food",num:632},
  {it:"filo",en:"wire",he:"[wire]",level:"B2",cat:"general",num:633},
  {it:"costo",en:"cost",he:"עלות",level:"B2",cat:"general",num:634},
  {it:"perso",en:"lost",he:"[lost]",level:"B2",cat:"general",num:635},
  {it:"marrone",en:"brown",he:"חום",level:"B2",cat:"adjectives",num:636},
  {it:"indossare",en:"wear",he:"[wear]",level:"B2",cat:"body",num:637},
  {it:"giardino",en:"garden",he:"גינה",level:"B2",cat:"places",num:638},
  {it:"pari",en:"equal",he:"[equal]",level:"B2",cat:"general",num:639},
  {it:"inviato",en:"sent",he:"[sent]",level:"B2",cat:"verbs",num:640},
  {it:"scegliere",en:"choose",he:"לבחור",level:"B2",cat:"verbs",num:641},
  {it:"caduto",en:"fell",he:"[fell]",level:"B2",cat:"verbs",num:642},
  {it:"adattarsi",en:"fit",he:"[fit]",level:"B2",cat:"verbs",num:643},
  {it:"flusso",en:"flow",he:"[flow]",level:"B2",cat:"general",num:644},
  {it:"fiera",en:"fair",he:"[fair]",level:"B2",cat:"general",num:645},
  {it:"banca",en:"bank",he:"בנק",level:"B2",cat:"places",num:646},
  {it:"raccogliere",en:"collect",he:"[collect]",level:"B2",cat:"verbs",num:647},
  {it:"salvare",en:"save",he:"[save]",level:"B2",cat:"verbs",num:648},
  {it:"controllo",en:"control",he:"[control]",level:"B2",cat:"general",num:649},
  {it:"decimale",en:"decimal",he:"[decimal]",level:"B2",cat:"general",num:650},
  {it:"orecchio",en:"ear",he:"אוזן",level:"B2",cat:"body",num:651},
  {it:"altro",en:"else",he:"אחר",level:"B2",cat:"adverbs",num:652},
  {it:"abbastanza",en:"quite",he:"די",level:"B2",cat:"adverbs",num:653},
  {it:"rotto",en:"broke",he:"שבור",level:"B2",cat:"general",num:654},
  {it:"caso",en:"case",he:"מקרה",level:"B2",cat:"general",num:655},
  {it:"mezzo",en:"middle",he:"אמצע",level:"B2",cat:"general",num:656},
  {it:"uccidere",en:"kill",he:"להרוג",level:"B2",cat:"verbs",num:657},
  {it:"figlio",en:"son",he:"בן",level:"B2",cat:"family",num:658},
  {it:"lago",en:"lake",he:"אגם",level:"B2",cat:"places",num:659},
  {it:"momento",en:"moment",he:"רגע",level:"B2",cat:"time",num:660},
  {it:"scala",en:"scale",he:"[scale]",level:"B2",cat:"general",num:661},
  {it:"forte",en:"loud",he:"רועש",level:"B2",cat:"adjectives",num:662},
  {it:"primavera",en:"spring",he:"אביב",level:"B2",cat:"time",num:663},
  {it:"osservare",en:"observe",he:"[observe]",level:"B2",cat:"verbs",num:664},
  {it:"bambino",en:"child",he:"ילד",level:"B2",cat:"family",num:665},
  {it:"dritto",en:"straight",he:"ישר",level:"B2",cat:"adjectives",num:666},
  {it:"consonante",en:"consonant",he:"[consonant]",level:"B2",cat:"family",num:667},
  {it:"nazione",en:"nation",he:"[nation]",level:"B2",cat:"general",num:668},
  {it:"dizionario",en:"dictionary",he:"[dictionary]",level:"B2",cat:"general",num:669},
  {it:"latte",en:"milk",he:"חלב",level:"B2",cat:"food",num:670},
  {it:"velocità",en:"speed",he:"מהירות",level:"B2",cat:"general",num:671},
  {it:"metodo",en:"method",he:"שיטה",level:"B2",cat:"general",num:672},
  {it:"organo",en:"organ",he:"[organ]",level:"B2",cat:"general",num:673},
  {it:"pagare",en:"pay",he:"לשלם",level:"B2",cat:"verbs",num:674},
  {it:"età",en:"age",he:"גיל",level:"B2",cat:"general",num:675},
  {it:"sezione",en:"section",he:"[section]",level:"B2",cat:"general",num:676},
  {it:"vestito",en:"dress",he:"שמלה",level:"B2",cat:"clothing",num:677},
  {it:"nube",en:"cloud",he:"[cloud]",level:"B2",cat:"general",num:678},
  {it:"sorpresa",en:"surprise",he:"[surprise]",level:"B2",cat:"general",num:679},
  {it:"tranquillo",en:"quiet",he:"שקט",level:"B2",cat:"adjectives",num:680},
  {it:"pietra",en:"stone",he:"אבן",level:"B2",cat:"general",num:681},
  {it:"piccolo",en:"tiny",he:"זעיר",level:"B2",cat:"adjectives",num:682},
  {it:"salita",en:"climb",he:"לטפס",level:"B2",cat:"verbs",num:683},
  {it:"fresco",en:"cool",he:"טרי",level:"B2",cat:"general",num:684},
  {it:"design",en:"design",he:"[design]",level:"B2",cat:"general",num:685},
  {it:"povero",en:"poor",he:"עני",level:"B2",cat:"adjectives",num:686},
  {it:"lotto",en:"lot",he:"[lot]",level:"B2",cat:"general",num:687},
  {it:"esperimento",en:"experiment",he:"[experiment]",level:"B2",cat:"general",num:688},
  {it:"fondo",en:"bottom",he:"למטה",level:"B2",cat:"general",num:689},
  {it:"chiave",en:"key",he:"מפתח",level:"B2",cat:"general",num:690},
  {it:"ferro",en:"iron",he:"ברזל",level:"B2",cat:"general",num:691},
  {it:"singolo",en:"single",he:"[single]",level:"B2",cat:"general",num:692},
  {it:"bastone",en:"stick",he:"[stick]",level:"B2",cat:"general",num:693},
  {it:"appartamento",en:"flat",he:"שטוח",level:"B2",cat:"adjectives",num:694},
  {it:"venti",en:"twenty",he:"[twenty]",level:"B2",cat:"general",num:695},
  {it:"pelle",en:"skin",he:"עור",level:"B2",cat:"body",num:696},
  {it:"sorriso",en:"smile",he:"לחייך",level:"B2",cat:"general",num:697},
  {it:"piega",en:"crease",he:"[crease]",level:"B2",cat:"general",num:698},
  {it:"foro",en:"hole",he:"[hole]",level:"B2",cat:"general",num:699},
  {it:"salto",en:"jump",he:"[jump]",level:"B2",cat:"general",num:700},
  {it:"bambino",en:"baby",he:"ילד",level:"B2",cat:"family",num:701},
  {it:"otto",en:"eight",he:"שמונה",level:"B2",cat:"numbers",num:702},
  {it:"villaggio",en:"village",he:"כפר",level:"B2",cat:"places",num:703},
  {it:"si incontrano",en:"meet",he:"[meet]",level:"B2",cat:"general",num:704},
  {it:"radice",en:"root",he:"[root]",level:"B2",cat:"general",num:705},
  {it:"acquistare",en:"buy",he:"לקנות",level:"B2",cat:"verbs",num:706},
  {it:"aumentare",en:"raise",he:"[raise]",level:"B2",cat:"verbs",num:707},
  {it:"risolvere",en:"solve",he:"לפתור",level:"B2",cat:"verbs",num:708},
  {it:"metallo",en:"metal",he:"[metal]",level:"B2",cat:"general",num:709},
  {it:"se",en:"whether",he:"אם",level:"B2",cat:"grammar",num:710},
  {it:"spingere",en:"push",he:"[push]",level:"B2",cat:"verbs",num:711},
  {it:"sette",en:"seven",he:"שבע",level:"B2",cat:"numbers",num:712},
  {it:"paragrafo",en:"paragraph",he:"[paragraph]",level:"B2",cat:"general",num:713},
  {it:"terzo",en:"third",he:"[third]",level:"B2",cat:"numbers",num:714},
  {it:"deve",en:"shall",he:"[shall]",level:"B2",cat:"general",num:715},
  {it:"tenuto",en:"held",he:"[held]",level:"B2",cat:"verbs",num:716},
  {it:"capelli",en:"hair",he:"שיער",level:"B2",cat:"body",num:717},
  {it:"descrivere",en:"describe",he:"[describe]",level:"B2",cat:"verbs",num:718},
  {it:"cuoco",en:"cook",he:"לבשל",level:"B2",cat:"food",num:719},
  {it:"piano",en:"floor",he:"תוכנית/מישור/פסנתר",level:"B2",cat:"general",num:720},
  {it:"o",en:"either",he:"[either]",level:"B2",cat:"general",num:721},
  {it:"risultato",en:"result",he:"תוצאה",level:"B2",cat:"verbs",num:722},
  {it:"bruciare",en:"burn",he:"[burn]",level:"B2",cat:"verbs",num:723},
  {it:"collina",en:"hill",he:"גבעה",level:"B2",cat:"general",num:724},
  {it:"sicuro",en:"safe",he:"בטוח",level:"B2",cat:"general",num:725},
  {it:"gatto",en:"cat",he:"חתול",level:"B2",cat:"animals",num:726},
  {it:"secolo",en:"century",he:"מאה",level:"B2",cat:"time",num:727},
  {it:"considerare",en:"consider",he:"[consider]",level:"B2",cat:"verbs",num:728},
  {it:"tipo",en:"type",he:"סוג",level:"B2",cat:"general",num:729},
  {it:"legge",en:"law",he:"חוק",level:"B2",cat:"general",num:730},
  {it:"bit",en:"bit",he:"קצת",level:"B2",cat:"general",num:731},
  {it:"costa",en:"coast",he:"חוף",level:"B2",cat:"general",num:732},
  {it:"copia",en:"copy",he:"[copy]",level:"B2",cat:"general",num:733},
  {it:"frase",en:"phrase",he:"משפט",level:"B2",cat:"general",num:734},
  {it:"silenzioso",en:"silent",he:"[silent]",level:"B2",cat:"general",num:735},
  {it:"alto",en:"tall",he:"גבוה",level:"B2",cat:"adjectives",num:736},
  {it:"sabbia",en:"sand",he:"[sand]",level:"B2",cat:"general",num:737},
  {it:"suolo",en:"soil",he:"[soil]",level:"B2",cat:"food",num:738},
  {it:"rotolo",en:"roll",he:"[roll]",level:"B2",cat:"general",num:739},
  {it:"temperatura",en:"temperature",he:"[temperature]",level:"B2",cat:"general",num:740},
  {it:"dito",en:"finger",he:"אצבע",level:"B2",cat:"body",num:741},
  {it:"industria",en:"industry",he:"תעשייה",level:"B2",cat:"general",num:742},
  {it:"valore",en:"value",he:"ערך",level:"B2",cat:"general",num:743},
  {it:"lotta",en:"fight",he:"קרב",level:"B2",cat:"general",num:744},
  {it:"bugia",en:"lie",he:"שקר",level:"B2",cat:"general",num:745},
  {it:"battere",en:"beat",he:"[beat]",level:"B2",cat:"verbs",num:746},
  {it:"eccitare",en:"excite",he:"[excite]",level:"B2",cat:"verbs",num:747},
  {it:"naturale",en:"natural",he:"טבעי",level:"B2",cat:"adjectives",num:748},
  {it:"vista",en:"view",he:"[view]",level:"B2",cat:"general",num:749},
  {it:"senso",en:"sense",he:"[sense]",level:"B2",cat:"general",num:750},
  {it:"capitale",en:"capital",he:"[capital]",level:"B2",cat:"general",num:751},
  {it:"non sarà",en:"won’t",he:"[won’t]",level:"B2",cat:"general",num:752},
  {it:"sedia",en:"chair",he:"כיסא",level:"B2",cat:"body",num:753},
  {it:"pericolo",en:"danger",he:"סכנה",level:"B2",cat:"general",num:754},
  {it:"frutta",en:"fruit",he:"פרי",level:"B2",cat:"food",num:755},
  {it:"ricco",en:"rich",he:"עשיר",level:"B2",cat:"adjectives",num:756},
  {it:"spesso",en:"thick",he:"עבה",level:"B2",cat:"adjectives",num:757},
  {it:"soldato",en:"soldier",he:"חייל",level:"B2",cat:"verbs",num:758},
  {it:"processo",en:"process",he:"תהליך",level:"B2",cat:"general",num:759},
  {it:"operare",en:"operate",he:"[operate]",level:"B2",cat:"verbs",num:760},
  {it:"pratica",en:"practice",he:"[practice]",level:"B2",cat:"general",num:761},
  {it:"separato",en:"separate",he:"[separate]",level:"B2",cat:"verbs",num:762},
  {it:"difficile",en:"difficult",he:"קשה",level:"B2",cat:"adjectives",num:763},
  {it:"medico",en:"doctor",he:"רופא",level:"B2",cat:"professions",num:764},
  {it:"per favore",en:"please",he:"[please]",level:"B2",cat:"general",num:765},
  {it:"proteggere",en:"protect",he:"להגן",level:"B2",cat:"verbs",num:766},
  {it:"mezzogiorno",en:"noon",he:"[noon]",level:"B2",cat:"general",num:767},
  {it:"raccolto",en:"crop",he:"[crop]",level:"B2",cat:"general",num:768},
  {it:"moderno",en:"modern",he:"מודרני",level:"B2",cat:"adjectives",num:769},
  {it:"elemento",en:"element",he:"[element]",level:"B2",cat:"general",num:770},
  {it:"colpire",en:"hit",he:"להכות",level:"B2",cat:"verbs",num:771},
  {it:"studente",en:"student",he:"תלמיד",level:"B2",cat:"professions",num:772},
  {it:"angolo",en:"corner",he:"פינה",level:"B2",cat:"general",num:773},
  {it:"partito",en:"party",he:"מסיבה",level:"B2",cat:"verbs",num:774},
  {it:"fornitura",en:"supply",he:"[supply]",level:"B2",cat:"general",num:775},
  {it:"la cui",en:"whose",he:"[whose]",level:"B2",cat:"grammar",num:776},
  {it:"individuare",en:"locate",he:"[locate]",level:"B2",cat:"verbs",num:777},
  {it:"anello",en:"ring",he:"טבעת",level:"B2",cat:"general",num:778},
  {it:"carattere",en:"character",he:"[character]",level:"B2",cat:"verbs",num:779},
  {it:"insetto",en:"insect",he:"[insect]",level:"B2",cat:"general",num:780},
  {it:"catturato",en:"caught",he:"[caught]",level:"B2",cat:"verbs",num:781},
  {it:"periodo",en:"period",he:"תקופה",level:"B2",cat:"time",num:782},
  {it:"indicare",en:"indicate",he:"לציין/להצביע",level:"B2",cat:"verbs",num:783},
  {it:"radio",en:"radio",he:"רדיו",level:"B2",cat:"general",num:784},
  {it:"raggio",en:"spoke",he:"[spoke]",level:"B2",cat:"general",num:785},
  {it:"atomo",en:"atom",he:"[atom]",level:"B2",cat:"general",num:786},
  {it:"umano",en:"human",he:"אנושי",level:"B2",cat:"adjectives",num:787},
  {it:"storia",en:"history",he:"היסטוריה",level:"B2",cat:"general",num:788},
  {it:"effetto",en:"effect",he:"אפקט",level:"B2",cat:"general",num:789},
  {it:"elettrico",en:"electric",he:"[electric]",level:"B2",cat:"general",num:790},
  {it:"aspettare",en:"expect",he:"לחכות",level:"B2",cat:"verbs",num:791},
  {it:"osso",en:"bone",he:"עצם",level:"B2",cat:"body",num:792},
  {it:"ferrovia",en:"rail",he:"[rail]",level:"B2",cat:"general",num:793},
  {it:"immaginare",en:"imagine",he:"[imagine]",level:"B2",cat:"verbs",num:794},
  {it:"fornire",en:"provide",he:"לספק",level:"B2",cat:"verbs",num:795},
  {it:"concordare",en:"agree",he:"[agree]",level:"B2",cat:"verbs",num:796},
  {it:"così",en:"thus",he:"כך",level:"B2",cat:"adverbs",num:797},
  {it:"dolce",en:"gentle",he:"מתוק",level:"B2",cat:"general",num:798},
  {it:"donna",en:"woman",he:"אישה",level:"B2",cat:"general",num:799},
  {it:"capitano",en:"captain",he:"[captain]",level:"B2",cat:"general",num:800},
  {it:"indovinare",en:"guess",he:"[guess]",level:"C1",cat:"verbs",num:801},
  {it:"necessario",en:"necessary",he:"הכרחי",level:"C1",cat:"adjectives",num:802},
  {it:"tagliente",en:"sharp",he:"חד",level:"C1",cat:"adjectives",num:803},
  {it:"ala",en:"wing",he:"[wing]",level:"C1",cat:"general",num:804},
  {it:"creare",en:"create",he:"ליצור",level:"C1",cat:"verbs",num:805},
  {it:"prossimo",en:"neighbor",he:"[neighbor]",level:"C1",cat:"general",num:806},
  {it:"lavaggio",en:"wash",he:"לשטוף",level:"C1",cat:"general",num:807},
  {it:"pipistrello",en:"bat",he:"[bat]",level:"C1",cat:"general",num:808},
  {it:"piuttosto",en:"rather",he:"די",level:"C1",cat:"adverbs",num:809},
  {it:"folla",en:"crowd",he:"[crowd]",level:"C1",cat:"general",num:810},
  {it:"mais",en:"corn",he:"[corn]",level:"C1",cat:"general",num:811},
  {it:"confrontare",en:"compare",he:"[compare]",level:"C1",cat:"verbs",num:812},
  {it:"poesia",en:"poem",he:"[poem]",level:"C1",cat:"general",num:813},
  {it:"stringa",en:"string",he:"[string]",level:"C1",cat:"general",num:814},
  {it:"campana",en:"bell",he:"[bell]",level:"C1",cat:"general",num:815},
  {it:"dipendere",en:"depend",he:"[depend]",level:"C1",cat:"verbs",num:816},
  {it:"carne",en:"meat",he:"בשר",level:"C1",cat:"food",num:817},
  {it:"strofinare",en:"rub",he:"[rub]",level:"C1",cat:"verbs",num:818},
  {it:"tubo",en:"tube",he:"[tube]",level:"C1",cat:"general",num:819},
  {it:"famoso",en:"famous",he:"[famous]",level:"C1",cat:"general",num:820},
  {it:"dollaro",en:"dollar",he:"[dollar]",level:"C1",cat:"general",num:921},
  {it:"ruscello",en:"stream",he:"[stream]",level:"C1",cat:"general",num:822},
  {it:"paura",en:"fear",he:"פחד",level:"C1",cat:"body",num:823},
  {it:"vista",en:"sight",he:"[sight]",level:"A2",cat:"general",num:284},
  {it:"sottile",en:"thin",he:"דק",level:"C1",cat:"adjectives",num:825},
  {it:"triangolo",en:"triangle",he:"[triangle]",level:"C1",cat:"general",num:826},
  {it:"pianeta",en:"planet",he:"כוכב לכת",level:"C1",cat:"general",num:827},
  {it:"fretta",en:"hurry",he:"[hurry]",level:"C1",cat:"general",num:828},
  {it:"capo",en:"chief",he:"בוס/ראש",level:"C1",cat:"general",num:829},
  {it:"colonia",en:"colony",he:"[colony]",level:"C1",cat:"general",num:830},
  {it:"orologio",en:"clock",he:"שעון",level:"C1",cat:"time",num:831},
  {it:"miniera",en:"mine",he:"[mine]",level:"C1",cat:"general",num:832},
  {it:"cravatta",en:"tie",he:"[tie]",level:"C1",cat:"clothing",num:833},
  {it:"inserire",en:"enter",he:"[enter]",level:"C1",cat:"verbs",num:834},
  {it:"maggiore",en:"major",he:"[major]",level:"C1",cat:"general",num:835},
  {it:"fresco",en:"fresh",he:"טרי",level:"C1",cat:"adjectives",num:836},
  {it:"ricerca",en:"search",he:"[search]",level:"C1",cat:"body",num:837},
  {it:"inviare",en:"send",he:"לשלוח",level:"C1",cat:"verbs",num:838},
  {it:"giallo",en:"yellow",he:"צהוב",level:"C1",cat:"adjectives",num:839},
  {it:"pistola",en:"gun",he:"[gun]",level:"C1",cat:"general",num:840},
  {it:"consentire",en:"allow",he:"לאפשר",level:"C1",cat:"verbs",num:841},
  {it:"stampa",en:"print",he:"עיתונות/דפוס",level:"C1",cat:"general",num:842},
  {it:"morto",en:"dead",he:"מת",level:"C1",cat:"adjectives",num:843},
  {it:"spot",en:"spot",he:"[spot]",level:"C1",cat:"general",num:844},
  {it:"deserto",en:"desert",he:"מדבר",level:"C1",cat:"places",num:845},
  {it:"tuta",en:"suit",he:"[suit]",level:"C1",cat:"clothing",num:846},
  {it:"corrente",en:"current",he:"נוכחי",level:"C1",cat:"adjectives",num:847},
  {it:"ascensore",en:"lift",he:"[lift]",level:"C1",cat:"general",num:848},
  {it:"rosa",en:"rose",he:"ורוד",level:"C1",cat:"general",num:840},
  {it:"arrivare",en:"arrive",he:"להגיע",level:"C1",cat:"verbs",num:850},
  {it:"master",en:"master",he:"[master]",level:"C1",cat:"general",num:851},
  {it:"pista",en:"track",he:"[track]",level:"C1",cat:"general",num:852},
  {it:"genitore",en:"parent",he:"[parent]",level:"C1",cat:"family",num:853},
  {it:"riva",en:"shore",he:"[shore]",level:"C1",cat:"general",num:854},
  {it:"divisione",en:"division",he:"[division]",level:"C1",cat:"general",num:855},
  {it:"foglio",en:"sheet",he:"[sheet]",level:"C1",cat:"general",num:856},
  {it:"sostanza",en:"substance",he:"[substance]",level:"C1",cat:"general",num:857},
  {it:"favorire",en:"favor",he:"[favor]",level:"C1",cat:"verbs",num:858},
  {it:"collegare",en:"connect",he:"[connect]",level:"C1",cat:"verbs",num:859},
  {it:"Messaggio",en:"post",he:"[post]",level:"C1",cat:"general",num:860},
  {it:"spendere",en:"spend",he:"להוציא/לבזבז",level:"C1",cat:"verbs",num:861},
  {it:"accordo",en:"chord",he:"[chord]",level:"C1",cat:"general",num:862},
  {it:"grasso",en:"fat",he:"[fat]",level:"C1",cat:"general",num:863},
  {it:"felice",en:"glad",he:"[glad]",level:"C1",cat:"general",num:864},
  {it:"originale",en:"original",he:"מקורי",level:"C1",cat:"adjectives",num:865},
  {it:"quota",en:"share",he:"[share]",level:"C1",cat:"general",num:866},
  {it:"stazione",en:"station",he:"תחנה",level:"C1",cat:"places",num:867},
  {it:"papà",en:"dad",he:"[dad]",level:"C1",cat:"general",num:868},
  {it:"pane",en:"bread",he:"לחם",level:"C1",cat:"food",num:869},
  {it:"carica",en:"charge",he:"[charge]",level:"C1",cat:"general",num:870},
  {it:"corretto",en:"proper",he:"נכון",level:"C1",cat:"general",num:871},
  {it:"bar",en:"bar",he:"[bar]",level:"C1",cat:"general",num:872},
  {it:"offerta",en:"offer",he:"להציע",level:"C1",cat:"general",num:873},
  {it:"segmento",en:"segment",he:"[segment]",level:"C1",cat:"general",num:874},
  {it:"schiavo",en:"slave",he:"[slave]",level:"C1",cat:"general",num:875},
  {it:"anatra",en:"duck",he:"[duck]",level:"C1",cat:"animals",num:876},
  {it:"immediato",en:"instant",he:"[instant]",level:"C1",cat:"verbs",num:877},
  {it:"mercato",en:"market",he:"שוק",level:"C1",cat:"places",num:878},
  {it:"grado",en:"degree",he:"מעלה",level:"C1",cat:"general",num:879},
  {it:"popolare",en:"populate",he:"פופולרי",level:"C1",cat:"verbs",num:880},
  {it:"pulcino",en:"chick",he:"[chick]",level:"C1",cat:"general",num:881},
  {it:"caro",en:"dear",he:"יקר",level:"C1",cat:"body",num:882},
  {it:"nemico",en:"enemy",he:"[enemy]",level:"C1",cat:"general",num:883},
  {it:"rispondere",en:"reply",he:"לענות",level:"C1",cat:"verbs",num:884},
  {it:"bevanda",en:"drink",he:"לשתות",level:"C1",cat:"general",num:885},
  {it:"verificarsi",en:"occur",he:"[occur]",level:"C1",cat:"verbs",num:886},
  {it:"supporto",en:"support",he:"[support]",level:"C1",cat:"places",num:887},
  {it:"discorso",en:"speech",he:"[speech]",level:"C1",cat:"general",num:888},
  {it:"natura",en:"nature",he:"טבע",level:"C1",cat:"general",num:889},
  {it:"gamma",en:"range",he:"[range]",level:"C1",cat:"general",num:890},
  {it:"vapore",en:"steam",he:"[steam]",level:"C1",cat:"food",num:891},
  {it:"moto",en:"motion",he:"[motion]",level:"C1",cat:"general",num:892},
  {it:"sentiero",en:"path",he:"[path]",level:"C1",cat:"general",num:893},
  {it:"liquido",en:"liquid",he:"[liquid]",level:"C1",cat:"general",num:894},
  {it:"log",en:"log",he:"[log]",level:"C1",cat:"general",num:895},
  {it:"significava",en:"meant",he:"[meant]",level:"C1",cat:"general",num:896},
  {it:"quoziente",en:"quotient",he:"[quotient]",level:"C1",cat:"clothing",num:897},
  {it:"denti",en:"teeth",he:"[teeth]",level:"C1",cat:"general",num:898},
  {it:"guscio",en:"shell",he:"[shell]",level:"C1",cat:"general",num:899},
  {it:"collo",en:"neck",he:"צוואר",level:"C1",cat:"body",num:900},
  {it:"ossigeno",en:"oxygen",he:"[oxygen]",level:"C1",cat:"general",num:901},
  {it:"zucchero",en:"sugar",he:"סוכר",level:"C1",cat:"food",num:902},
  {it:"morte",en:"death",he:"מוות",level:"C1",cat:"general",num:903},
  {it:"piuttosto",en:"pretty",he:"די",level:"C1",cat:"adjectives",num:904},
  {it:"abilità",en:"skill",he:"[skill]",level:"C1",cat:"general",num:905},
  {it:"donne",en:"women",he:"[women]",level:"C1",cat:"general",num:906},
  {it:"stagione",en:"season",he:"[season]",level:"C1",cat:"time",num:907},
  {it:"soluzione",en:"solution",he:"[solution]",level:"C1",cat:"general",num:908},
  {it:"magnete",en:"magnet",he:"[magnet]",level:"C1",cat:"general",num:909},
  {it:"argento",en:"silver",he:"כסף",level:"C1",cat:"general",num:910},
  {it:"grazie",en:"thank",he:"[thank]",level:"C1",cat:"general",num:911},
  {it:"ramo",en:"branch",he:"[branch]",level:"C1",cat:"general",num:912},
  {it:"partita",en:"match",he:"משחק",level:"C1",cat:"verbs",num:913},
  {it:"suffisso",en:"suffix",he:"[suffix]",level:"C1",cat:"general",num:914},
  {it:"particolarmente",en:"especially",he:"במיוחד",level:"C1",cat:"adverbs",num:915},
  {it:"fico",en:"fig",he:"[fig]",level:"C1",cat:"general",num:916},
  {it:"impaurito",en:"afraid",he:"[afraid]",level:"C1",cat:"verbs",num:917},
  {it:"enorme",en:"huge",he:"ענק",level:"C1",cat:"adjectives",num:918},
  {it:"sorella",en:"sister",he:"אחות",level:"C1",cat:"family",num:919},
  {it:"acciaio",en:"steel",he:"[steel]",level:"C1",cat:"general",num:920},
  {it:"discutere",en:"discuss",he:"[discuss]",level:"C1",cat:"verbs",num:921},
  {it:"avanti",en:"forward",he:"קדימה",level:"C1",cat:"adverbs",num:922},
  {it:"simile",en:"similar",he:"דומה",level:"C1",cat:"adjectives",num:923},
  {it:"guidare",en:"guide",he:"לנהוג",level:"C1",cat:"verbs",num:924},
  {it:"esperienza",en:"experience",he:"[experience]",level:"C1",cat:"general",num:925},
  {it:"punteggio",en:"score (noun)",he:"[score (noun)]",level:"C1",cat:"general",num:926},
  {it:"mela",en:"apple",he:"תפוח",level:"C1",cat:"food",num:927},
  {it:"comprato",en:"bought",he:"[bought]",level:"C1",cat:"verbs",num:928},
  {it:"portato",en:"led",he:"הובא",level:"C1",cat:"verbs",num:929},
  {it:"pece",en:"pitch",he:"[pitch]",level:"C1",cat:"general",num:930},
  {it:"cappotto",en:"coat",he:"מעיל",level:"C1",cat:"clothing",num:931},
  {it:"massa",en:"mass",he:"[mass]",level:"C1",cat:"general",num:932},
  {it:"scheda",en:"card",he:"[card]",level:"C1",cat:"transport",num:933},
  {it:"banda",en:"band (rubber)",he:"[band (rubber)]",level:"C1",cat:"general",num:934},
  {it:"corda",en:"rope",he:"[rope]",level:"C1",cat:"general",num:935},
  {it:"slittamento",en:"slip",he:"[slip]",level:"C1",cat:"general",num:936},
  {it:"vittoria",en:"win",he:"לנצח",level:"C1",cat:"general",num:937},
  {it:"sognare",en:"dream",he:"חלום",level:"C1",cat:"verbs",num:938},
  {it:"sera",en:"evening",he:"ערב",level:"C1",cat:"time",num:939},
  {it:"condizione",en:"condition",he:"מצב",level:"C1",cat:"general",num:940},
  {it:"alimentazione",en:"feed",he:"[feed]",level:"C1",cat:"general",num:941},
  {it:"strumento",en:"tool",he:"כלי",level:"C1",cat:"general",num:942},
  {it:"totale",en:"total",he:"כולל",level:"C1",cat:"adjectives",num:943},
  {it:"di base",en:"basic",he:"[basic]",level:"C1",cat:"general",num:944},
  {it:"odore",en:"smell",he:"[smell]",level:"C1",cat:"general",num:945},
  {it:"valle",en:"valley",he:"עמק",level:"C1",cat:"general",num:946},
  {it:"né",en:"nor",he:"[nor]",level:"C1",cat:"general",num:947},
  {it:"doppio",en:"double",he:"[double]",level:"C1",cat:"general",num:948},
  {it:"sedile",en:"seat (in a car)",he:"[seat (in a car)]",level:"C1",cat:"transport",num:949},
  {it:"continuare",en:"continue",he:"להמשיך",level:"C1",cat:"verbs",num:950},
  {it:"blocco",en:"a block",he:"[a block]",level:"C1",cat:"general",num:951},
  {it:"grafico",en:"chart",he:"[chart]",level:"C1",cat:"general",num:952},
  {it:"cappello",en:"hat",he:"כובע",level:"C1",cat:"clothing",num:953},
  {it:"vendere",en:"sell",he:"למכור",level:"C1",cat:"verbs",num:954},
  {it:"successo",en:"success",he:"[success]",level:"C1",cat:"general",num:955},
  {it:"azienda",en:"a company",he:"[a company]",level:"C1",cat:"general",num:956},
  {it:"sottrarre",en:"subtract",he:"[subtract]",level:"C1",cat:"general",num:957},
  {it:"evento",en:"event",he:"[event]",level:"C1",cat:"general",num:958},
  {it:"particolare",en:"particular",he:"מסוים",level:"C1",cat:"adjectives",num:959},
  {it:"affare",en:"deal",he:"[deal]",level:"C1",cat:"verbs",num:960},
  {it:"nuoto",en:"swim",he:"לשחות",level:"C1",cat:"general",num:961},
  {it:"termine",en:"term",he:"[term]",level:"C1",cat:"general",num:962},
  {it:"opposto",en:"opposite",he:"[opposite]",level:"C1",cat:"general",num:963},
  {it:"moglie",en:"wife",he:"אישה",level:"C1",cat:"family",num:964},
  {it:"scarpa",en:"shoe",he:"נעל",level:"C1",cat:"clothing",num:965},
  {it:"spalla",en:"shoulder",he:"כתף",level:"C1",cat:"body",num:966},
  {it:"spargere",en:"spread",he:"להפיץ",level:"C1",cat:"verbs",num:967},
  {it:"organizzare",en:"arrange",he:"לארגן",level:"C1",cat:"verbs",num:968},
  {it:"campo",en:"a camp",he:"[a camp]",level:"C1",cat:"general",num:969},
  {it:"inventare",en:"invent",he:"[invent]",level:"C1",cat:"verbs",num:970},
  {it:"cotone",en:"cotton",he:"[cotton]",level:"C1",cat:"general",num:971},
  {it:"nascita",en:"birth",he:"[birth]",level:"C1",cat:"verbs",num:972},
  {it:"determinare",en:"determine",he:"לקבוע",level:"C1",cat:"verbs",num:973},
  {it:"quarto di gallone",en:"quart",he:"[quart]",level:"C1",cat:"general",num:974},
  {it:"nove",en:"nine",he:"תשע",level:"C1",cat:"numbers",num:975},
  {it:"camion",en:"truck",he:"[truck]",level:"C1",cat:"transport",num:976},
  {it:"rumore",en:"noise",he:"[noise]",level:"C1",cat:"general",num:977},
  {it:"livello",en:"level",he:"רמה",level:"C1",cat:"general",num:978},
  {it:"possibilità",en:"a chance",he:"[a chance]",level:"C1",cat:"general",num:979},
  {it:"raccogliere",en:"gather",he:"[gather]",level:"C1",cat:"verbs",num:980},
  {it:"negozio",en:"a shop",he:"חנות",level:"C1",cat:"places",num:981},
  {it:"tratto",en:"stretch (of land)",he:"[stretch (of land)]",level:"C1",cat:"general",num:982},
  {it:"gettare",en:"throw",he:"[throw]",level:"C1",cat:"verbs",num:983},
  {it:"brillare",en:"shine",he:"[shine]",level:"C1",cat:"verbs",num:984},
  {it:"proprietà",en:"property",he:"נכס/רכוש",level:"C1",cat:"general",num:985},
  {it:"colonna",en:"column",he:"[column]",level:"C1",cat:"general",num:986},
  {it:"molecola",en:"molecule",he:"[molecule]",level:"C1",cat:"general",num:987},
  {it:"selezionare",en:"select",he:"[select]",level:"C1",cat:"verbs",num:988},
  {it:"sbagliato",en:"wrong",he:"לא נכון",level:"C1",cat:"adjectives",num:989},
  {it:"grigio",en:"gray",he:"אפור",level:"C1",cat:"adjectives",num:990},
  {it:"ripetizione",en:"repeat",he:"לחזור",level:"C1",cat:"general",num:991},
  {it:"richiedere",en:"require",he:"לדרוש",level:"C1",cat:"verbs",num:992},
  {it:"ampio",en:"broad",he:"רחב",level:"C1",cat:"places",num:993},
  {it:"preparare",en:"prepare",he:"להכין",level:"C1",cat:"verbs",num:994},
  {it:"sale",en:"salt",he:"מלח",level:"C1",cat:"food",num:995},
  {it:"naso",en:"nose",he:"אף",level:"C1",cat:"body",num:996},
  {it:"plurale",en:"plural",he:"רבים",level:"C1",cat:"general",num:997},
  {it:"rabbia",en:"anger",he:"כעס",level:"C1",cat:"general",num:998},
  {it:"richiesta",en:"claim",he:"תביעה",level:"C1",cat:"general",num:999},
  {it:"continente",en:"continent",he:"יבשת",level:"C1",cat:"general",num:1000}
];

const CATEGORIES = {
  pronouns: "כינויים",
  grammar: "דקדוק",
  verbs: "פעלים",
  numbers: "מספרים",
  time: "זמן",
  food: "אוכל ושתייה",
  body: "גוף",
  family: "משפחה",
  places: "מקומות",
  clothing: "בגדים",
  transport: "תחבורה",
  adjectives: "תארים",
  adverbs: "תוארי פועל",
  animals: "חיות",
  professions: "מקצועות",
  general: "כללי",
};

const CATEGORY_ICONS = {
  pronouns: "👤",
  grammar: "📝",
  verbs: "⚡",
  numbers: "🔢",
  time: "⏰",
  food: "🍕",
  body: "🫀",
  family: "👨‍👩‍👧‍👦",
  places: "🏠",
  clothing: "👔",
  transport: "🚗",
  adjectives: "🎨",
  adverbs: "💨",
  animals: "🐾",
  professions: "👨‍⚕️",
  general: "📌",
};

const LEVEL_COLORS = { A1: "#4CAF50", A2: "#2196F3", B1: "#FF9800", B2: "#F44336", C1: "#9C27B0" };

const PHRASES = [
  {level:"A1",it:"Io sono italiano.",he:"אני איטלקי.",en:"I am Italian."},
  {level:"A1",it:"Come ti chiami?",he:"איך קוראים לך?",en:"What is your name?"},
  {level:"A1",it:"Mi chiamo Marco.",he:"קוראים לי מרקו.",en:"My name is Marco."},
  {level:"A1",it:"Piacere di conoscerti.",he:"נעים להכיר אותך.",en:"Nice to meet you."},
  {level:"A1",it:"Da dove vieni?",he:"מאיפה אתה?",en:"Where are you from?"},
  {level:"A1",it:"Vengo da Roma.",he:"אני מרומא.",en:"I come from Rome."},
  {level:"A1",it:"Buongiorno!",he:"בוקר טוב!",en:"Good morning!"},
  {level:"A1",it:"Buonasera!",he:"ערב טוב!",en:"Good evening!"},
  {level:"A1",it:"Buonanotte!",he:"לילה טוב!",en:"Good night!"},
  {level:"A1",it:"Arrivederci!",he:"להתראות!",en:"Goodbye!"},
  {level:"A1",it:"Grazie mille!",he:"תודה רבה!",en:"Thank you very much!"},
  {level:"A1",it:"Prego!",he:"בבקשה!",en:"You\'re welcome!"},
  {level:"A1",it:"Scusa!",he:"סליחה!",en:"Excuse me!"},
  {level:"A1",it:"Non capisco.",he:"אני לא מבין.",en:"I don\'t understand."},
  {level:"A1",it:"Parla inglese?",he:"האם אתה מדבר אנגלית?",en:"Do you speak English?"},
  {level:"A1",it:"Non parlo italiano bene.",he:"אני לא מדבר איטלקית טוב.",en:"I don\'t speak Italian well."},
  {level:"A1",it:"Più lentamente, per favore.",he:"יותר לאט, בבקשה.",en:"More slowly, please."},
  {level:"A1",it:"Molto bene!",he:"מאוד טוב!",en:"Very good!"},
  {level:"A1",it:"Che bello!",he:"איזה יופי!",en:"How beautiful!"},
  {level:"A1",it:"Quanti anni hai?",he:"בן כמה אתה?",en:"How old are you?"},
  {level:"A1",it:"Dove abiti?",he:"איפה אתה גר?",en:"Where do you live?"},
  {level:"A1",it:"Abito a Milano.",he:"אני גר במילאנו.",en:"I live in Milan."},
  {level:"A1",it:"Così così.",he:"ככה-ככה.",en:"So-so."},
  {level:"A1",it:"Ho ventitre anni.",he:"אני בן עשרים ושלוש.",en:"I am twenty-three years old."},
  {level:"A1",it:"Può ripetere, per favore?",he:"אתה יכול לחזור בבקשה?",en:"Can you repeat, please?"},
  {level:"A2",it:"Vorrei un caffè, per favore.",he:"אני רוצה קפה, בבקשה.",en:"I would like a coffee, please."},
  {level:"A2",it:"Quanto costa?",he:"כמה זה עולה?",en:"How much does it cost?"},
  {level:"A2",it:"Posso pagare con la carta?",he:"אפשר לשלם בכרטיס?",en:"Can I pay with a card?"},
  {level:"A2",it:"Il conto, per favore.",he:"החשבון, בבקשה.",en:"The bill, please."},
  {level:"A2",it:"Dov\'è la stazione?",he:"איפה התחנה?",en:"Where is the station?"},
  {level:"A2",it:"A che ora apre?",he:"באיזו שעה נפתח?",en:"What time does it open?"},
  {level:"A2",it:"Ho bisogno di aiuto.",he:"אני צריך עזרה.",en:"I need help."},
  {level:"A2",it:"Mi sono perso.",he:"אני הלכתי לאיבוד.",en:"I am lost."},
  {level:"A2",it:"Che tempo fa oggi?",he:"איזה מזג אוויר יש היום?",en:"What\'s the weather today?"},
  {level:"A2",it:"Fa caldo oggi.",he:"חם היום.",en:"It\'s hot today."},
  {level:"A2",it:"Mi fa male la testa.",he:"כואלת לי הראש.",en:"I have a headache."},
  {level:"A2",it:"Sono stanco.",he:"אני עייף.",en:"I am tired."},
  {level:"A2",it:"Andiamo al cinema?",he:"נלך לקולנוע?",en:"Shall we go to the cinema?"},
  {level:"A2",it:"Ti piace la pizza?",he:"אתה אוהב פיצה?",en:"Do you like pizza?"},
  {level:"A2",it:"Sì, mi piace molto.",he:"כן, אני מאוד אוהב.",en:"Yes, I like it a lot."},
  {level:"B1",it:"Secondo me, questo è un buon libro.",he:"לדעתי, זה ספר טוב.",en:"In my opinion, this is a good book."},
  {level:"B1",it:"Mi piacerebbe visitare l\'Italia.",he:"הייתי רוצה לבקר באיטליה.",en:"I would like to visit Italy."},
  {level:"B1",it:"Sto studiando l\'italiano da due anni.",he:"אני לומד איטלקית כבר שנתיים.",en:"I\'ve been studying Italian for two years."},
  {level:"B1",it:"Se potessi, viaggerei di più.",he:"אם הייתי יכול, הייתי נוסע יותר.",en:"If I could, I would travel more."},
  {level:"B1",it:"Penso che sia una buona idea.",he:"אני חושב שזו רעיון טוב.",en:"I think it\'s a good idea."},
  {level:"B1",it:"Avrei dovuto studiare di più.",he:"הייתי צריך ללמוד יותר.",en:"I should have studied more."},
  {level:"B1",it:"Nonostante il traffico, siamo arrivati in tempo.",he:"למרות התנועה, הגענו בזמן.",en:"Despite the traffic, we arrived on time."},
  {level:"B1",it:"Mi dispiace che tu non possa venire.",he:"חבל שאתה לא יכול לבוא.",en:"I\'m sorry you can\'t come."},
  {level:"B1",it:"È da tanto che non ti vedo!",he:"לא ראיתי אותך הרבה זמן!",en:"Long time no see!"},
  {level:"B2",it:"A meno che non piova, usciremo.",he:"אלא אם יירד גשם, נצא.",en:"Unless it rains, we\'ll go out."},
  {level:"B2",it:"Non solo è intelligente, ma anche lavoratore.",he:"לא רק שהוא חכם, אלא גם חרוץ.",en:"Not only smart, but also hardworking."},
  {level:"B2",it:"Per quanto ne so, la situazione è sotto controllo.",he:"עד כמה שאני יודע, המצב בשליטה.",en:"As far as I know, it\'s under control."},
  {level:"B2",it:"Qualunque cosa succeda, sarò lì.",he:"מה שלא יקרה, אני אהיה שם.",en:"Whatever happens, I\'ll be there."},
  {level:"B2",it:"Più studi, più impari.",he:"ככל שתלמד יותר, כך תלמד יותר.",en:"The more you study, the more you learn."},
  {level:"C1",it:"Per l\'appunto, volevo parlarti proprio di questo.",he:"בדיוק, רציתי לדבר איתך בדיוק על זה.",en:"As a matter of fact, I wanted to talk about this."},
  {level:"C1",it:"Ad ogni modo, non credo che sia la soluzione giusta.",he:"בכל מקרה, אני לא חושב שזו הפתרון הנכון.",en:"Anyway, I don\'t think it\'s the right solution."},
  {level:"C1",it:"A dire il vero, non me l\'aspettavo.",he:"בכנות, לא ציפיתי לזה.",en:"To tell the truth, I didn\'t expect it."},
  {level:"C1",it:"Per concludere, vorrei ringraziare tutti.",he:"לסיכום, הייתי רוצה להודות לכולם.",en:"In conclusion, I would like to thank everyone."}
];

const APP_DATA = {
  words: WORDS,
  sentences: PHRASES.map(p => ({...p, cat: p.level === "A1" ? "pronouns" : p.level === "A2" ? "general" : "verbs"})),
  skillTree: [
    {id:"A1_adjectives",level:"A1",name:"תארים",icon:"🎨",category:"adjectives",prerequisite:null,wordCount:20},
    {id:"A1_adverbs",level:"A1",name:"תוארי פועל",icon:"💨",category:"adverbs",prerequisite:"A1_adjectives",wordCount:18},
    {id:"A1_body",level:"A1",name:"גוף",icon:"🫀",category:"body",prerequisite:"A1_adverbs",wordCount:4},
    {id:"A1_clothing",level:"A1",name:"בגדים",icon:"👔",category:"clothing",prerequisite:"A1_body",wordCount:1},
    {id:"A1_family",level:"A1",name:"משפחה",icon:"👨‍👩‍👧‍👦",category:"family",prerequisite:"A1_clothing",wordCount:2},
    {id:"A1_food",level:"A1",name:"אוכל ושתייה",icon:"🍕",category:"food",prerequisite:"A1_family",wordCount:1},
    {id:"A1_general",level:"A1",name:"כללי",icon:"📌",category:"general",prerequisite:"A1_food",wordCount:52},
    {id:"A1_grammar",level:"A1",name:"דקדוק",icon:"📝",category:"grammar",prerequisite:"A1_general",wordCount:31},
    {id:"A1_numbers",level:"A1",name:"מספרים",icon:"🔢",category:"numbers",prerequisite:"A1_grammar",wordCount:3},
    {id:"A1_places",level:"A1",name:"מקומות",icon:"🏠",category:"places",prerequisite:"A1_numbers",wordCount:2},
    {id:"A1_pronouns",level:"A1",name:"כינויים",icon:"👤",category:"pronouns",prerequisite:"A1_places",wordCount:21},
    {id:"A1_time",level:"A1",name:"זמן",icon:"⏰",category:"time",prerequisite:"A1_pronouns",wordCount:3},
    {id:"A1_transport",level:"A1",name:"תחבורה",icon:"🚗",category:"transport",prerequisite:"A1_time",wordCount:1},
    {id:"A1_verbs",level:"A1",name:"פעלים",icon:"⚡",category:"verbs",prerequisite:"A1_transport",wordCount:41},
    {id:"A2_adjectives",level:"A2",name:"תארים",icon:"🎨",category:"adjectives",prerequisite:"A1_verbs",wordCount:27},
    {id:"A2_adverbs",level:"A2",name:"תוארי פועל",icon:"💨",category:"adverbs",prerequisite:"A2_adjectives",wordCount:7},
    {id:"A2_animals",level:"A2",name:"חיות",icon:"🐾",category:"animals",prerequisite:"A2_adverbs",wordCount:3},
    {id:"A2_body",level:"A2",name:"גוף",icon:"🫀",category:"body",prerequisite:"A2_animals",wordCount:9},
    {id:"A2_family",level:"A2",name:"משפחה",icon:"👨‍👩‍👧‍👦",category:"family",prerequisite:"A2_body",wordCount:3},
    {id:"A2_food",level:"A2",name:"אוכל ושתייה",icon:"🍕",category:"food",prerequisite:"A2_family",wordCount:3},
    {id:"A2_general",level:"A2",name:"כללי",icon:"📌",category:"general",prerequisite:"A2_food",wordCount:93},
    {id:"A2_grammar",level:"A2",name:"דקדוק",icon:"📝",category:"grammar",prerequisite:"A2_general",wordCount:6},
    {id:"A2_numbers",level:"A2",name:"מספרים",icon:"🔢",category:"numbers",prerequisite:"A2_grammar",wordCount:3},
    {id:"A2_places",level:"A2",name:"מקומות",icon:"🏠",category:"places",prerequisite:"A2_numbers",wordCount:8},
    {id:"A2_pronouns",level:"A2",name:"כינויים",icon:"👤",category:"pronouns",prerequisite:"A2_places",wordCount:1},
    {id:"A2_time",level:"A2",name:"זמן",icon:"⏰",category:"time",prerequisite:"A2_pronouns",wordCount:1},
    {id:"A2_transport",level:"A2",name:"תחבורה",icon:"🚗",category:"transport",prerequisite:"A2_time",wordCount:6},
    {id:"A2_verbs",level:"A2",name:"פעלים",icon:"⚡",category:"verbs",prerequisite:"A2_transport",wordCount:31},
    {id:"B1_adjectives",level:"B1",name:"תארים",icon:"🎨",category:"adjectives",prerequisite:"A2_verbs",wordCount:19},
    {id:"B1_adverbs",level:"B1",name:"תוארי פועל",icon:"💨",category:"adverbs",prerequisite:"B1_adjectives",wordCount:3},
    {id:"B1_animals",level:"B1",name:"חיות",icon:"🐾",category:"animals",prerequisite:"B1_adverbs",wordCount:1},
    {id:"B1_body",level:"B1",name:"גוף",icon:"🫀",category:"body",prerequisite:"B1_animals",wordCount:9},
    {id:"B1_family",level:"B1",name:"משפחה",icon:"👨‍👩‍👧‍👦",category:"family",prerequisite:"B1_body",wordCount:3},
    {id:"B1_food",level:"B1",name:"אוכל ושתייה",icon:"🍕",category:"food",prerequisite:"B1_family",wordCount:2},
    {id:"B1_general",level:"B1",name:"כללי",icon:"📌",category:"general",prerequisite:"B1_food",wordCount:107},
    {id:"B1_grammar",level:"B1",name:"דקדוק",icon:"📝",category:"grammar",prerequisite:"B1_general",wordCount:4},
    {id:"B1_numbers",level:"B1",name:"מספרים",icon:"🔢",category:"numbers",prerequisite:"B1_grammar",wordCount:5},
    {id:"B1_places",level:"B1",name:"מקומות",icon:"🏠",category:"places",prerequisite:"B1_numbers",wordCount:7},
    {id:"B1_time",level:"B1",name:"זמן",icon:"⏰",category:"time",prerequisite:"B1_places",wordCount:7},
    {id:"B1_transport",level:"B1",name:"תחבורה",icon:"🚗",category:"transport",prerequisite:"B1_time",wordCount:2},
    {id:"B1_verbs",level:"B1",name:"פעלים",icon:"⚡",category:"verbs",prerequisite:"B1_transport",wordCount:31},
    {id:"B2_adjectives",level:"B2",name:"תארים",icon:"🎨",category:"adjectives",prerequisite:"B1_verbs",wordCount:15},
    {id:"B2_adverbs",level:"B2",name:"תוארי פועל",icon:"💨",category:"adverbs",prerequisite:"B2_adjectives",wordCount:4},
    {id:"B2_animals",level:"B2",name:"חיות",icon:"🐾",category:"animals",prerequisite:"B2_adverbs",wordCount:1},
    {id:"B2_body",level:"B2",name:"גוף",icon:"🫀",category:"body",prerequisite:"B2_animals",wordCount:9},
    {id:"B2_clothing",level:"B2",name:"בגדים",icon:"👔",category:"clothing",prerequisite:"B2_body",wordCount:1},
    {id:"B2_family",level:"B2",name:"משפחה",icon:"👨‍👩‍👧‍👦",category:"family",prerequisite:"B2_clothing",wordCount:4},
    {id:"B2_food",level:"B2",name:"אוכל ושתייה",icon:"🍕",category:"food",prerequisite:"B2_family",wordCount:6},
    {id:"B2_general",level:"B2",name:"כללי",icon:"📌",category:"general",prerequisite:"B2_food",wordCount:98},
    {id:"B2_grammar",level:"B2",name:"דקדוק",icon:"📝",category:"grammar",prerequisite:"B2_general",wordCount:2},
    {id:"B2_numbers",level:"B2",name:"מספרים",icon:"🔢",category:"numbers",prerequisite:"B2_grammar",wordCount:3},
    {id:"B2_places",level:"B2",name:"מקומות",icon:"🏠",category:"places",prerequisite:"B2_numbers",wordCount:5},
    {id:"B2_professions",level:"B2",name:"מקצועות",icon:"👨‍⚕️",category:"professions",prerequisite:"B2_places",wordCount:2},
    {id:"B2_time",level:"B2",name:"זמן",icon:"⏰",category:"time",prerequisite:"B2_professions",wordCount:4},
    {id:"B2_transport",level:"B2",name:"תחבורה",icon:"🚗",category:"transport",prerequisite:"B2_time",wordCount:1},
    {id:"B2_verbs",level:"B2",name:"פעלים",icon:"⚡",category:"verbs",prerequisite:"B2_transport",wordCount:45},
    {id:"C1_adjectives",level:"C1",name:"תארים",icon:"🎨",category:"adjectives",prerequisite:"B2_verbs",wordCount:15},
    {id:"C1_adverbs",level:"C1",name:"תוארי פועל",icon:"💨",category:"adverbs",prerequisite:"C1_adjectives",wordCount:3},
    {id:"C1_animals",level:"C1",name:"חיות",icon:"🐾",category:"animals",prerequisite:"C1_adverbs",wordCount:1},
    {id:"C1_body",level:"C1",name:"גוף",icon:"🫀",category:"body",prerequisite:"C1_animals",wordCount:6},
    {id:"C1_clothing",level:"C1",name:"בגדים",icon:"👔",category:"clothing",prerequisite:"C1_body",wordCount:6},
    {id:"C1_family",level:"C1",name:"משפחה",icon:"👨‍👩‍👧‍👦",category:"family",prerequisite:"C1_clothing",wordCount:3},
    {id:"C1_food",level:"C1",name:"אוכל ושתייה",icon:"🍕",category:"food",prerequisite:"C1_family",wordCount:6},
    {id:"C1_general",level:"C1",name:"כללי",icon:"📌",category:"general",prerequisite:"C1_food",wordCount:109},
    {id:"C1_numbers",level:"C1",name:"מספרים",icon:"🔢",category:"numbers",prerequisite:"C1_general",wordCount:1},
    {id:"C1_places",level:"C1",name:"מקומות",icon:"🏠",category:"places",prerequisite:"C1_numbers",wordCount:6},
    {id:"C1_time",level:"C1",name:"זמן",icon:"⏰",category:"time",prerequisite:"C1_places",wordCount:3},
    {id:"C1_transport",level:"C1",name:"תחבורה",icon:"🚗",category:"transport",prerequisite:"C1_time",wordCount:3},
    {id:"C1_verbs",level:"C1",name:"פעלים",icon:"⚡",category:"verbs",prerequisite:"C1_transport",wordCount:37}
  ],
  achievements: [
    {id:"first_login",name:"התחלה חדשה",icon:"🌱",desc:"התחברת פעם ראשונה"},
    {id:"first_quiz",name:"חידון ראשון",icon:"🎯",desc:"סיימת חידון ראשון"},
    {id:"streak3",name:"3 ימים רצופים",icon:"🔥",desc:"למדת 3 ימים ברצף"},
    {id:"streak7",name:"שבוע שלם!",icon:"💪",desc:"למדת 7 ימים ברצף"},
    {id:"streak30",name:"חודש אלוף!",icon:"👑",desc:"למדת 30 ימים ברצף"},
    {id:"words50",name:"50 מילים",icon:"📚",desc:"למדת 50 מילים"},
    {id:"words100",name:"100 מילים",icon:"📖",desc:"למדת 100 מילים"},
    {id:"words500",name:"500 מילים",icon:"🎓",desc:"למדת 500 מילים"},
    {id:"words1000",name:"מילון חי!",icon:"🏅",desc:"למדת 1000 מילים"},
    {id:"crown5",name:"5 כתרים",icon:"👑",desc:"השגת 5 כתרים"},
    {id:"perfect_quiz",name:"חידון מושלם",icon:"⭐",desc:"ציון 100% בחידון"},
    {id:"game10",name:"שחקן ותיק",icon:"🎮",desc:"שיחקת 10 משחקים"}
  ],
  dialogues: [
    {id:"bar_a1",level:"A1",cat:"food",title:"בבר 🍷",lines:[{role:"npc",it:"Buongiorno! Cosa desidera bere?",he:"בוקר טוב! מה תרצה לשתות?"}, {role:"you",it:"Vorrei un caffè, per favore.",he:"אני רוצה קפה, בבקשה."}, {role:"npc",it:"Americano o espresso?",he:"אמריקנו או אספרסו?"}, {role:"you",it:"Un espresso, grazie.",he:"אספרסו, תודה."}, {role:"npc",it:"Va bene! Subito!",he:"בסדר! מיד!"}]},
    {id:"pharmacy_a2",level:"A2",cat:"body",title:"בבית מרקחת 💊",lines:[{role:"npc",it:"Buongiorno, come posso aiutarla?",he:"בוקר טוב, איך אוכל לעזור?"}, {role:"you",it:"Mi fa male la testa. Ha qualcosa?",he:"כואלת לי הראש. יש לך משהו?"}, {role:"npc",it:"Sì, questa pastiglia è molto efficace.",he:"כן, הגלולה הזו מאוד יעילה."}, {role:"you",it:"Quanto costa?",he:"כמה זה עולה?"}, {role:"npc",it:"Cinque euro. Prego!",he:"חמישה אירו. בבקשה!"}]},
    {id:"restaurant_b1",level:"B1",cat:"food",title:"במסעדה 🍝",lines:[{role:"npc",it:"Buonasera! Un tavolo per due?",he:"ערב טוב! שולחן לשניים?"}, {role:"you",it:"Sì, grazie. Possiamo vedere il menu?",he:"כן, תודה. אפשר לראות את התפריט?"}, {role:"npc",it:"Certamente! Ecco il menu.",he:"בוודאי! הנה התפריט."}, {role:"you",it:"Vorrei la carbonara, per favore.",he:"אני רוצה קרבונרה, בבקשה."}, {role:"npc",it:"Ottima scelta! Da bere?",he:"בחירה מעולה! מה לשתות?"}, {role:"you",it:"Un bicchiere di vino rosso.",he:"כוס יין אדום."}, {role:"npc",it:"Perfetto! Arriva subito.",he:"מושלם! מגיע מיד."}]},
    {id:"market_b1",level:"B1",cat:"food",title:"בשוק 🍅",lines:[{role:"npc",it:"Buongiorno! Le mele sono freschissime oggi!",he:"בוקר טוב! התפוחים מאוד טריים היום!"}, {role:"you",it:"Quanto costano?",he:"כמה הם עולים?"}, {role:"npc",it:"Due euro al chilo.",he:"שני אירו לקילו."}, {role:"you",it:"Me ne dia due chili, per favore.",he:"תן לי שני קילו, בבקשה."}, {role:"npc",it:"Ecco qua! Arrivederci!",he:"הנה! להתראות!"}]}
  ],
  cilsExams: [
    {level:"A1",name:"CILS A1",sections:["אזנה", "קריאה", "כתיבה", "דיבור"],time:"50 דקות"},
    {level:"A2",name:"CILS A2",sections:["אזנה", "קריאה", "כתיבה", "דיבור"],time:"80 דקות"},
    {level:"B1",name:"CILS B1",sections:["אזנה", "קריאה", "כתיבה", "דיבור"],time:"120 דקות"},
    {level:"B2",name:"CILS B2",sections:["אזנה", "קריאה", "כתיבה", "דיבור"],time:"150 דקות"},
    {level:"C1",name:"CILS C1",sections:["אזנה", "קריאה", "כתיבה", "דיבור"],time:"180 דקות"}
  ],
  newsItems: [
    {title:"Il Colosseo: un simbolo di Roma",titleHe:"הקולוסיאום: סמל של רומא",desc:"Il Colosseo è l\'anfiteatro più grande del mondo.",descHe:"הקולוסיאום הוא האמפיתיאטרון הגדול בעולם."},
    {title:"La pizza napoletana è patrimonio UNESCO",titleHe:"הפיצה הנפוליטנית היא מורשת יונסק\"ו",desc:"L\'arte del pizzaiolo napoletano è riconosciuta dall\'UNESCO.",descHe:"אמנות הפיצאיולו הנפוליטני מוכרת על ידי אונסק\"ו."},
    {title:"Il gelato italiano: una tradizione",titleHe:"הג\'לטו האיטלקי: מסורת",desc:"Il gelato artigianale è una specialità italiana amata in tutto il mondo.",descHe:"ג\'לטו אומנותי הוא מומחיות איטלקית אהובה בכל העולם."},
    {title:"Venezia e i suoi canali",titleHe:"ונציה והתעלות שלה",desc:"Venezia è costruita su 118 piccole isole collegate da ponti.",descHe:"ונציה בנויה על 118 איים קטנים המחוברים בגשרים."},
    {title:"La moda italiana",titleHe:"האופנה האיטלקית",desc:"Milano è una delle capitali della moda nel mondo.",descHe:"מילאנו היא אחת מבירות האופנה בעולם."}
  ],
  songs: [
    {title:"Volare",artist:"Domenico Modugno",level:"A1",lyrics:"Nel blu dipinto di blu\nFelice di stare lassù",lyricsHe:"בכחול צבוע בכחול\nשמח להיות שם למעלה"},
    {title:"Con te partirò",artist:"Andrea Bocelli",level:"A2",lyrics:"Con te partirò\nPaesi che non ho mai\nVeduto e vissuto con te",lyricsHe:"איתך אצא לדרך\nלמדינות שמעולם לא\nראיתי וחייתי איתך"},
    {title:"Caruso",artist:"Lucio Dalla",level:"B1",lyrics:"Te voglio bene assai\nMa tanto tanto bene sai",lyricsHe:"אוהב אותך מאוד\nאבל כל כך הרבה, את יודעת"}
  ],
  stories: [
    {id:"rome_story",title:"יום ברומא",level:"A1",icon:"🏛️",paragraphs:[{it:"Oggi Maria va a Roma. Roma è una città bellissima.",he:"היום מריה נוסעת לרומא. רומא היא עיר יפהפייה."}, {it:"Visita il Colosseo e mangia una pizza.",he:"היא מבקרת בקולוסיאום ואוכלת פיצה."}, {it:"La sera, passeggia vicino al Tevere.",he:"בערב, היא מטיילת ליד הטיבר."}]},
    {id:"florence_story",title:"ביקור בפירנצה",level:"A2",icon:"🎨",paragraphs:[{it:"Marco arriva a Firenze in treno. La città è piena d\'arte.",he:"מרקו מגיע לפירנצה ברכבת. העיר מלאה באמנות."}, {it:"Visita la Galleria degli Uffizi e ammira i dipinti del Rinascimento.",he:"הוא מבקר בגלריה אופיצי ומתפעל מציורי הרנסאנס."}, {it:"Dopo, compra un gelato e passeggia sul Ponte Vecchio.",he:"אחר כך, הוא קונה ג\'לטו ומטייל על גשר וקיו."}]}
  ],
  culture: [
    {title:"ברכות איטלקיות",icon:"🤝",level:"A1",items:["Ciao — היי/להתראות", "Buongiorno — בוקר טוב", "Buonasera — ערב טוב", "Arrivederci — להתראות"]},
    {title:"אוכל איטלקי",icon:"🍝",level:"A1",items:["La colazione — ארוחת בוקר", "Il pranzo — ארוחת צהריים", "La cena — ארוחת ערב", "L\'antipasto — מנה ראשונה"]},
    {title:"ג\'סטות איטלקיות",icon:"🤌",level:"A2",items:["מצמד אצבעות — מה זה אומר?", "לנשק לחי — ברכת שלום", "להניד ראש — לא מסכים", "ידיים באוויר — השתגעתי!"]}
  ],
};